### PR TITLE
[Add] nrf52_factory_erase submodule

### PR DESCRIPTION
**Pull request by markbirss**
This is the platformio version of the meshtastic nrf52 factory erase firmware (previous version was based on arduino)

builds same as meshtastic firmware with 2 variants available
* s140_nrf52_611_softdevice
* s140_nrf52_730_softdevice

e.g
./bin/build-nrf52.sh s140_nrf52_611_softdevice
 
then find files in release directory

### CODE REVIEW

**Comment by markbirss** [comment]
@caveman99 
kindly have a look at this PR

**Comment by thebentern** [comment]
@markbirss any interest in transfer the repo for the submodule to the Meshtastic org?

**Comment by markbirss** [comment]
> @markbirss any interest in transfer the repo for the submodule to the Meshtastic org?

Sure

**Comment by markbirss** [comment]
> @markbirss any interest in transfer the repo for the submodule to the Meshtastic org?

Moving repository to meshtastic/nrf52_factory_erase. This may take a few minutes.

**Pull request closed without merging**
