### PR TITLE
Added modifier key combination to allow keyboard shortcuts on t-deck

### PR DESCRIPTION
**Pull request by nbaddorf**
The keyboard on the t-deck does not have a 'tab' button or a function button for triggering keyboard shortcuts. I added a 'modifier' key combo that is triggered by pressing shift and the mic (0) button on t-decks keyboard. Then press the letter for the shortcut you want. Currently implemented is: q (quit or cancel), t (tab), and m (mute/unmute).

### CODE REVIEW

**Comment by nbaddorf** [comment]
All that the mute and tab code I added do are return the key code for that function, it doesnt actually change any values. All the t-deck thinks is that you are pressing the tab button or a mute button which just so happens to not actually have a phisical button on the keyboard. The code that actually handles the tab and mute functions are in the CannedMessagesModule.cpp

My t-deck did reboot once when I tried muting it, but it has worked fine since then but there may be some bugs in the CannedMessages to figure out with that.

**Comment by nbaddorf** [comment]
Related to the added functionality of the 'tab' key, we can remove two lines in the CannedMessagesModule.cpp which were forcing the node and channel selection to only change nodes. 

On line 164 and 167 of the CannedMessagesModule.cpp you can remove these two lines: `this->destSelect = CANNED_MESSAGE_DESTINATION_TYPE_NODE;` 

Now when typing a message, toggle the tab function once to change nodes (swipe touchscreen or trackball to change nodes) or toggle the tab again to change which channels you are sending on.

**Comment by caveman99** [comment]
The T-Deck keyboard is quite dumb, comparable to the BBQ10 beyboard we support as well. I just now got a t-deck and intend to port the bbq10 code to it, making sure both keyboards behave the same. It's a similar approach, just with different key combos.
I'd incorporate these suggestions...

**Comment by ChDel** [comment]
> The keyboard on the t-deck does not have a 'tab' button or a function button for triggering keyboard shortcuts. I added a 'modifier' key combo that is triggered by pressing shift and the mic (0) button on t-decks keyboard. Then press the letter for the shortcut you want. Currently implemented is: q (quit or cancel), t (tab), and m (mute/unmute).

That is amazing! 
While you are there, is there any chances you could add shortcuts to increase and decrease the screen brightness? On a sunny day ☀️, there is no way to see anything outside and there is currently no way to change the brightness at all... 
🙏

**Comment by caveman99** [comment]
@nbaddorf the t-deck kb code is really retarded. I didn't mange to make shift-mic work, however shift-speaker will issue the 0x04 scancode for me. (0x24 minus 0x20) - there are really no other scancodes that are sent from the KB to the host, except alt-c

Short of flashing a decent kb firmware to the t-deck (which is not something the average user would do) - what do you think of alt+c as a trigger/escape? it's easier to hit than either shift-mic or shift-speaker...

**Comment by nbaddorf** [comment]
I also started working on adding brightness shortcuts. I think the screen is default set to the brightest setting so keep that in mind as I dont think it will be getting any brighter. There is currently code implemented using the OLEDDisplay library for setting brightness. I added functions and keyboard shortcuts to change brightness but the OLEDDisplay library doesnt apear to be set to the backlight pin for the t-decks display. It looks like the backlight is currently being set high from digitalWrite but I dont remember where I found that. I can continue looking into changing that implementation to use the OLEDDisplay command.

**Comment by ChDel** [comment]
> I also started working on adding brightness shortcuts. I think the screen is default set to the brightest setting so keep that in mind as I dont think it will be getting any brighter. There is currently code implemented using the OLEDDisplay library for setting brightness. I added functions and keyboard shortcuts to change brightness but the OLEDDisplay library doesnt apear to be set to the backlight pin for the t-decks display. It looks like the backlight is currently being set high from digitalWrite but I dont remember where I found that. I can continue looking into changing that implementation to use the OLEDDisplay command.

Thank you so much for that! 🙏 
From what I was told by 2 people working on the firmware, the brightness is set at 50%... So we can still hope to get some brightness out of it hopefully :) 
This is beyond my scope of expertise, So I really appreciate you taking the time...

**Comment by caveman99** [comment]
> I did just notice that one of the t-decks keyboards has more symbols for a different language on it as well as not having the $ symbol printed on the keyboard.

The keypads they sue in these are not makde any more, this is repair/surplus stock from the Blackberry Company. So they are switching to international layouts right now after they ran out of US keypads. the innards are mostly the same. My additonal chars look like Thai symbols, but i have seen arabic too. Don't worry about that too much, you can't control it anyway.

**Comment by nbaddorf** [comment]
I added brightness code! Use the modifier key with o(+) or i(-) to change brightness between 4 levels (low, medium low (default), medium high, high). I would like to add a popup message that displays the current brightness when you change it.

I would appreciate any sugestions on how I could improve the location of definition for "uint8_t brightness" because I get a warning when compiling that it could be uninitialized although I don't see how it could not be initialized, and havent had any issues. Maybe it is a simple fix I wasnt thinking about. Thanks!

**Comment by caveman99** [comment]
Looks good to me - for the text popups, look at the code that was just added to CannedMessages a few days back. You can utilize that.

**Review by caveman99 — APPROVED** [review]

**Comment by nbaddorf** [comment]
Thanks Caveman99. I looked through CannedMessages but couldnt find any new code. Are you maybe refering to this pull request? https://github.com/meshtastic/firmware/pull/3627

As for a delay when setting the brightness to max, I have no idea what could be causing that, both of my t-decks work just fine with no delay.

**Comment by nbaddorf** [comment]
I would love yalls input, I just added some code to display usefull info in the bottom right corner of the screen like if notifications are muted. Are there any other symbals (letters, not images) that would be usefull to display? Should I even keep this addition? It does sometimes take a second for the symbol to show up, but it is generally pretty quick.

I also changed how the keyboard shortcuts were sent to CannedMessages. I added a MODKEY value so that functions we want like muting notifications or changing brightness does not reset the display back to the default screen. 

Finally I fixed the warning about potentially undefined brightness value.

**Comment by nbaddorf** [comment]
Hey, thinking about it after the fact, I wasn't verry happy with some of the code in my previous implementation so I changed part of it making it simpler, and I dont think it will cause any issues with other devices. Id apretiate it if you would test it and let me know if you have any concerns. I think I am finally done chainging this unless yall want me too! 

I do see that there is an issue on Github saying that I have conflicts with CannedMessages perticually with the mute notification function. I moved that modifier code to a different location in the file (along with most of the others) to make it work without setting the screen back to the default display. If I have to change something there let me know.

I did just see that there was a pull request accepted which added a line to a function I moved so I may have to add that in. (This is my first pull request and I am no master programmer (age 19) so any suggestions would be appreciated.) Thanks!

**Comment by ChrDel** [comment]
Is there any hold backs on merging this?

**Comment by thebentern** [comment]
> Is there any hold backs on merging this? 

Upstream has some changes so we are waiting for the author to resolve the merge conflicts

**Comment by nbaddorf** [comment]
Sorry, I have been rather busy at home. I will try to get this fixed.

**Comment by GeneralZodGit** [comment]
After updating my T-Deck to 2.3.7 I can no longer swipe left and right or use the ball to change channels. Also, none of the keyboard shortcuts listed here work as written at all. So, unless I connect via bluetooth with a phone, I can only send to the broadcast primary channel now... Shift-0 or ALT-C plus T don't work.

**Review by thebentern — APPROVED** [review]

**Comment by joneyes** [comment]
> From what I was told by 2 people working on the firmware, the brightness is set at 50%... So we can still hope to get some brightness out of it hopefully :) 
> This is beyond my scope of expertise, So I really appreciate you taking the time...

The default use of green makes it harder to read.
I found editing src/graphics/TFTDisplay.cpp to bring the color565 hex values to FF (which is white), the screen was far more readable.
I'm not sure if this impacts any other implementations.

I'm a bit of a long in the tooth noob and botched the pull request and havent got around to having another. Happy for someone else to fix it properly.

**Comment by caveman99** [comment]
> The default use of green makes it harder to read. I found editing src/graphics/TFTDisplay.cpp to bring the color565 hex values to FF (which is white), the screen was far more readable. I'm not sure if this impacts any other implementations.

That's what `#define TFT_MESH COLOR565(0xFF, 0xFF, 0xFF)` in the variant file is for. The picomputer uses it.

**Comment by joneyes** [comment]
OK, so it's perfectly feasible to add #define TFT_MESH COLOR565(0xFF, 0xFF, 0xFF) to the T-Deck variant.h file? That will override the default green values of TFT_MESH COLOR565(0x67, 0xEA, 0x94) in TFTDisplay.cpp?

**Comment by caveman99** [comment]
yes, that should work. If it doesan't the macro was not added in every screen definiton but that can be rectified :-)

**Comment by joneyes** [comment]
> yes, that should work. If it doesan't the macro was not added in every screen definiton but that can be rectified :-)

It appears to have worked OK on my T-Deck.
See pull request #3926

**Pull request merged**
