### PR TITLE
- implement shutdown (deep sleep forever) on ESP32

### PR DESCRIPTION
**Pull request by caveman99**
- Clean up shutdown and delayed shutdown code conditionals.
- clean up inputbroker includes

### CODE REVIEW

**Comment by caveman99** [comment]
this implements #2326

**Comment by garthvh** [comment]
Yay!

**Review by garthvh — APPROVED** [review]

**Review by thebentern — APPROVED** [review]
Looks good. Only thing I'd add is make sure to add the HAS_CPU_SHUTDOWN to architecture.h for esp32 platform like we have in NRF for metadata responses so clients can know that they can now send shutdown admin messages

**Comment by mc-hamster** [comment]
"woops" ... lol :)

**Pull request merged**
