### PR TITLE
Add Panel_ILI9342 to TFTDisplay.cpp

### PR DESCRIPTION
**Pull request by lboue**
We had to add [Panel_ILI9342](https://github.com/lovyan03/LovyanGFX/blob/master/src/lgfx/v1/panel/Panel_ILI9342.hpp) to fix this request: [[Feature Request]: ILITEK ILI9342 LCD screen #4821](https://github.com/meshtastic/firmware/issues/4821)

### CODE REVIEW

**Comment by fifieldt** [comment]
Hi,

looking quickly at the driver code in TFTDisplay.cpp, the code for ILI9341_DRIVER and ILI9342_DRIVER looks almost identical. Though, I could be missing something!

Would you consider re-using some of the existing code there?

**Comment by fifieldt** [comment]
Ah! I see this is draft :) Please ignore me if you haven't made the changes yet :)

**Comment by lboue** [comment]
> Hi,
> 
> looking quickly at the driver code in TFTDisplay.cpp, the code for ILI9341_DRIVER and ILI9342_DRIVER looks almost identical. Though, I could be missing something!
> 
> Would you consider re-using some of the existing code there?

OK, I'll try to factorize the code.

**Comment by lboue** [comment]
> > Hi,
> > looking quickly at the driver code in TFTDisplay.cpp, the code for ILI9341_DRIVER and ILI9342_DRIVER looks almost identical. Though, I could be missing something!
> > Would you consider re-using some of the existing code there?
> 
> OK, I'll try to factorize the code.

Is it OK now?

**Comment by fifieldt** [comment]
Thanks so much for doing that. Taking a look.

**Review by fifieldt — APPROVED** [review]

**Review by thebentern — APPROVED** [review]

**Pull request merged**
