### PR TITLE
Add a Userprefs Timezone String, to be replaced in the web flasher

### PR DESCRIPTION
**Pull request by jp-bennett**

### CODE REVIEW

**Review by thebentern — APPROVED** [review]

**Review by thebentern — APPROVED** [review]

**Comment by GUVWAF** [comment]
Maybe we can do the same with the `BUILD_TIME` macro? Currently it's still rebuilding the whole firmware every time, because this changes in the platformio.ini file.

**Comment by GUVWAF** [comment]
Maybe we can do the same with the `BUILD_TIME` macro? Currently it's still rebuilding the whole firmware every time, because this changes in the platformio.ini file.

**Comment by thebentern** [comment]
> Maybe we can do the same with the `BUILD_EPOCH` macro? Currently it's still rebuilding the whole firmware every time, because this changes in the platformio.ini file.

GENIUS! I've been almost regretting the mechanism for that one because I'm commenting it out locally to avoid rebuilds. 🤣

**Comment by thebentern** [comment]
Actually I think I have a quick way of fixing this the BUILD_EPOCH. PR incoming!

**Pull request merged**
