### PR TITLE
NodeInfo broadcast ensure default on 0 and enforce 1 hour minimum

### PR DESCRIPTION
**Pull request by thebentern**
As discussed in #transport-layer room.

Also removed some of the no_save cruft that's been an eye-sore.

### CODE REVIEW

**Review by GUVWAF — APPROVED** [review]
Looks good. We should document this and probably recommend enabling smart position for "wardriving".

**Comment by caveman99** [comment]
> Also removed some of the no_save cruft that's been an eye-sore.

Does anybody actually use this? if it was for me we can throw it out completely. Also the module presets in source comments...

**Comment by thebentern** [comment]
I do not. I've maybe used it once in the past 3 years. I suspect Kevin used it a lot in earlier development of the project.
Should we get rid of the no_save on device state protos? I don't believe anybody else uses it.

> > Also removed some of the no_save cruft that's been an eye-sore.
> 
> Does anybody actually use this? if it was for me we can throw it out completely. Also the module presets in source comments...

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/settings-for-driving-around-to-find-other-nodes/7525/10

**Pull request merged**
