### PR TITLE
Add Notification on device screen following feature toggle

### PR DESCRIPTION
**Pull request by HarukiToreda**
[Feature Request]: Add display messages on device screen following feature toggle #3551 requested by @tropho23 

I was able partly complete this request. 

**1. Fn+M:**  Shows "Notifications Enabled" / "Notifications Dissabled
**2. Fn+Space:** Shows "Ping Broadcasted" I didn't think it would be correct to say "Updated position sent to mesh" since it's really adhoc Ping.
**3. Fn+G:** Shows "GPS Toggled" - I could not add on or off since the code only toggles and does not check what state the gps is at originally. Would like some advice on this to make it more accurate.

**Issue:** although the Nofications show on the screen as intended, I have not been able to make the Notifcations dissapear after 2 seconds, it remains on the screen until you press either ESC/Enter or press the Program button, If anyone has any advice on how to make it automatic, I would really appreaciate the assist.

Notifications

### CODE REVIEW

**Comment by tropho23** [comment]
Thank you for these additions!

I will offer that for Fn + Space, yes we do send an adhoc ping but it is sent primarily for the purpose of sending updated position data, so perhaps a shortened version of my suggestion would be better.  Maybe "Position update sent", or even "Telemetry update sent" if an adhoc ping contains more than just position data?

I think @caveman99 might know the secret to making notifications disappear, as he implemented that for delivery confirmations (if that was him).

Tony Good
________________________________
From: HarukiToreda ***@***.***>
Sent: Monday, April 15, 2024 00:13
To: meshtastic/firmware ***@***.***>
Cc: tropho23 ***@***.***>; Mention ***@***.***>
Subject: [meshtastic/firmware] Add display messages on device screen following feature toggle (PR #3627)


[Feature Request]: Add display messages on device screen following feature toggle #3551<https://github.com/meshtastic/firmware/issues/3551> requested by @tropho23<https://github.com/tropho23>

I was able partly complete this request.

1. Fn+M: Shows "Notifications Enabled" / "Notifications Dissabled
2. Fn+Space: Shows "Ping Broadcasted" I didn't think it would be correct to say "Updated position sent to mesh" since it's really adhoc Ping.
3. Fn+G: Shows "GPS Toggled" - I could not add on or off since the code only toggles and does not check what state the gps is at originally. Would like some advice on this to make it more accurate.

Issue: although the Nofications show on the screen as intended, I have not been able to make the Notifcations dissapear after 2 seconds, it remains on the screen until you press either ESC/Enter or press the Program button, If anyone has any advice on how to make it automatic, I would really appreaciate the assist.

Notifications.png (view on web)<https://github.com/meshtastic/firmware/assets/116696711/dae1e41b-485a-40e4-9950-281058b7f0b9>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/meshtastic/firmware/pull/3627

Commit Summary

  *   7064dc6<https://github.com/meshtastic/firmware/pull/3627/commits/7064dc61fe1f3d1b30349e8b6cccf84eb234770c> Update CannedMessageModule.h
  *   b33d84c<https://github.com/meshtastic/firmware/pull/3627/commits/b33d84cc7560764441f01786ef945cb4777d6391> Update CannedMessageModule.cpp

File Changes

(2 files<https://github.com/meshtastic/firmware/pull/3627/files>)

  *   M src/modules/CannedMessageModule.cpp<https://github.com/meshtastic/firmware/pull/3627/files#diff-caf0a45c5c8826739fb7f9d175b3867d8a7c7a2d8709457f96a8c271a10ddcb8> (27)
  *   M src/modules/CannedMessageModule.h<https://github.com/meshtastic/firmware/pull/3627/files#diff-311da9d753c5b5b11a9f93b3611bb0090cda4abe119370a354ca88a40cb1e3d3> (5)

Patch Links:

  *   https://github.com/meshtastic/firmware/pull/3627.patch
  *   https://github.com/meshtastic/firmware/pull/3627.diff

**Comment by caveman99** [comment]
@HarukiToreda can you test this branch? i don't have a device at hand ... white collar code, hoping it will work.

**Comment by HarukiToreda** [comment]
> @HarukiToreda can you test this branch? i don't have a device at hand ... white collar code, hoping it will work.

I just built it, the notifications no longer appear unfortunately.

**Comment by caveman99** [comment]
I'll dig a t-beam out tomorrow ... i guess just a small oversight ...

**Comment by caveman99** [comment]
@HarukiToreda confirmed working over here. please check :-)

**Comment by HarukiToreda** [comment]
> @HarukiToreda confirmed working over here. please check :-)

Confirmed working on my side too. Thank you

**Comment by HarukiToreda** [comment]
> > **2. Fn+Space:** Shows "Ping Broadcasted" I didn't think it would be correct to say "Updated position sent to mesh" since it's really adhoc Ping.
> 
> This one is actually showing
> 
> ```
> "Telemetry \nUpdate Sent"
> ```
> 
> The rest appear to work as intended though.

yes, this is a change that @tropho23 requested earlier

**Pull request merged**
