### PR TITLE
Make serial port on wio-sdk-wm1110 board work

### PR DESCRIPTION
**Pull request by geeksville**
By disabling the (inaccessible) adafruit USB

### CODE REVIEW

**Comment by geeksville** [comment]
oh - anyone know if it possible to suppress trunk checks on a particular python script?  the script that failed is used by platformio directly and is valid when imported in that environment.  alternatively I could delete  it for now...

**Comment by caveman99** [comment]
Depends on the failing linter. Most either support online comments or a point file in the trunk subdir.

**Comment by geeksville** [comment]
ok - i'll read up on trunk. no prob.

**Comment by thebentern** [comment]
To be honest, it wouldn't hurt my feelings if we turned trunk off altogether on the python scripts. I'm not a fan off all of the linting of configuration and scripting languages. Seems excessive.

**Review by thebentern — APPROVED** [review]

**Review by caveman99 — APPROVED** [review]

**Pull request merged**
