### PR TITLE
Update the Heltec board battery level read accuracy.

### PR DESCRIPTION
**Pull request by Heltec-Aaron-Lee**
Update the Heltec board battery voltage read parameter.

### CODE REVIEW

**Comment by HarukiToreda** [comment]
> Update the Heltec board battery voltage read parameter.

Hey Aaron, you need to sign the CLA for this to be pushed.

**Comment by Cisien** [comment]
I can confirm these values work as an override in the current firmware by setting the override to 5.1205 (4.9*1.045)

**Comment by mkgin** [comment]
"*1.045" 5 bytes of bureaucracy...

**Comment by garthvh** [comment]
Hi @Heltec-Aaron-Lee we really need access to the fork of meshtastic you are giving out to customers, needs to be available per the GPL3, it appears that the protobufs are out of sync and this is becoming a support issue.  We also need the CLA signed before this can get merged.

**Comment by Heltec-Aaron-Lee** [comment]
Hi @garthvh sorry for the delay. It is already signed, I will pay attention to it in the future.

**Pull request merged**
