### PR TITLE
Add Ethernet RAK13800 support to RAK11310

### PR DESCRIPTION
**Pull request by beegee-tokyo**
Cleanup pins_arduino.h of RAK11310
Add Ethernet capability to variant.h of RAK11310
Add RAK11310/RAK13800 support to ethClient.cpp

Add RAK11310 variant to platformio.ini.
_Requires long file name support on Windows 11 **and** git_ ==> [Filename too long in Git for Windows](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows)

> Open a PowerShell window/console, and run the following:
- Setting Registry Value:

```sh
# Check LongPathsEnabled settings
Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled

# If 0, set it to 1 - This is a System wide configuration
# This will fail if you do not have Admin priveleges
# Changes to CurrentControlSet\Control take effect after a system restart
$MyPSexe = Get-Process -PID $PID | % Path
Start-Process -Verb RunAs $MyPSexe "-c","Set-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Type DWord -Value 1"
```

> Setting git config --system - System wide for all Windows users:

```sh
Start-Process -Verb RunAs "git" "config","--system","core.longpaths","true"
& git config "--global" core.longpaths true
```

### CODE REVIEW

**Review by fifieldt — APPROVED** [review]

**Review by caveman99 — APPROVED** [review]

**Comment by caveman99** [comment]
Thanks for the pointers to the windows changes. This is neccessary for every rp2040 based build. I'll add this to the developer documentation.

**Comment by beegee-tokyo** [comment]
> Thanks for the pointers to the windows changes. This is neccessary for every rp2040 based build. I'll add this to the developer documentation.

You're welcome.
Stumbled over this before when I started using earls' repo.

**Comment by Nivek-domo** [comment]
> Cleanup pins_arduino.h of RAK11310 Add Ethernet capability to variant.h of RAK11310 Add RAK11310/RAK13800 support to ethClient.cpp
> 
> Add RAK11310 variant to platformio.ini. _Requires long file name support on Windows 11 **and** git_ ==> [Filename too long in Git for Windows](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows)
> 
> > Open a PowerShell window/console, and run the following:
> 
> * Setting Registry Value:
> 
> ```shell
> # Check LongPathsEnabled settings
> Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled
> 
> # If 0, set it to 1 - This is a System wide configuration
> # This will fail if you do not have Admin priveleges
> # Changes to CurrentControlSet\Control take effect after a system restart
> $MyPSexe = Get-Process -PID $PID | % Path
> Start-Process -Verb RunAs $MyPSexe "-c","Set-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Type DWord -Value 1"
> ```
> 
> > Setting git config --system - System wide for all Windows users:
> 
> ```shell
> Start-Process -Verb RunAs "git" "config","--system","core.longpaths","true"
> & git config "--global" core.longpaths true
> ```

i test your modif, but fr work well i need to change 2 other files, /scr/mesh/api ServerAPI.h and .cpp i replace #if RAK_4631 by #if defined(RAK_4631) || defined(RAK11310) and now it work very well

**Comment by Nivek-domo** [comment]
i test your modif, but fr work well i need to change 2 other files, /scr/mesh/api ServerAPI.h and .cpp i replace #if RAK_4631 by #if defined(RAK_4631) || defined(RAK11310) and now it work very well ligne 61, 78 of ServerAPI.cpp et ligne 46 ServerAPI.h

**Pull request merged**
