### PR TITLE
Cleanup for Air530z GPS

### PR DESCRIPTION
**Pull request by fifieldt**
It turns out that the Air530z is a GNSS_MODEL_MTK. Our existing code detects and configures it properly. This patch removes a couple of AIROHA ifdefs since they are not required for a working GPS.

### CODE REVIEW

**Comment by markbirss** [comment]
@fifieldt This change also affects Tracker T1000-e GPS

**Comment by fifieldt** [comment]
yes @markbirss , I believe setting #define GPS_BAUDRATE 115200 in the T1000e variant.h is incorrect: the Air530z defaults to 9600. Try removing that line?

**Comment by markbirss** [comment]
> yes @markbirss , I believe setting #define GPS\_BAUDRATE 115200 in the T1000e variant.h is incorrect: the Air530z defaults to 9600. Try removing that line?

Does not seem to help.

**Comment by fifieldt** [comment]
What's breaking? What is it detecting as? Can you confirm if the Air530 in the T1000E is the same as the Air530 available for sale from the Seeed store (I.e. an Air530z)?

**Comment by markbirss** [comment]
@failed "Failed to find UBlox & MTK GNSS Module using baudrate"

I cannot confirm only have T1000-E

@Dylanliacc can you confirm ?

**Comment by fifieldt** [comment]
Thanks for looking at it. If it's not too much trouble, what are the baud rates it tries?

**Comment by markbirss** [comment]
It does try couple 9600,4800, 57600 and 115200

DEBUG | ??:??:?? 2 \[GPS\] Probing for GPS at 9600                                   
WARN  | ??:??:?? 6 \[GPS\] Failed to find UBlox & MTK GNSS Module using baudrate 9  
600

**Comment by fifieldt** [comment]
Working on something I think will fix t1000e

https://github.com/meshtastic/firmware/compare/master...fifieldt:meshtastic-firmware:l89-2

**Comment by fifieldt** [comment]
Working on the fix in #4394

**Pull request merged**
