### PR TITLE
Move NeighborInfo interval default to 6 hours (double NodeInfo)

### PR DESCRIPTION
**Pull request by thebentern**
As a part of the default MQTT broker traffic management, we've noticed a disproportionate percentage of packets lately are NeighborInfo. Given that this data is really only useful for mesh topology visualizations, I'm proposing moving it to a 6-hour interval, which is double that of its most similar companion: NodeInfo.

### CODE REVIEW

**Comment by garthvh** [comment]
Do 6, twice a day is fine

**Comment by thebentern** [comment]
I agree. Sounds good. So we'll double both the node info broadcast interval default and minimum allowed.

**Comment by jp-bennett** [comment]
@thebentern Take a second look at this. I think you accidentally dropped the ms to second scaling, so Neighborinfo happens about 1000 times more often than intended.

**Comment by Talie5in** [comment]
> @thebentern Take a second look at this. I think you accidentally dropped the ms to second scaling, so Neighborinfo happens about 1000 times more often than intended.

Can confirm, opened a Issue
https://github.com/meshtastic/firmware/issues/4502

**Pull request merged**
