### PR TITLE
feat(variants): Add support for TXCO on TLORA_V2_1_6 devices

### PR DESCRIPTION
**Pull request by Scarg**
## Description

Add support for LILYGO®LoRa V2.1_1.6 devices that come with TCXO following LILYGO's examples (see [here](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/examples/RadioLibExamples/SX1276/SX1276_Receive_Interrupt/boards.h#L338)).

Before these changes, the device didn't work properly and instead reported **`Critical fault #3`**.

## Notes

Creating a new variant seemed like the correct solution as it was the easiest way to handle the removal of pin 33 from LORA_DIO1.
Instead of creating an entirely new `variant.h`, something that seemed overkill as they are otherwise the same device, I simply created a new platform and added an extra build flag while still basing the environment on the default V2.1_1.6 variant definition.

I would have preferred to not touch LORA_DIO1, especially since I'm not sure what should be the correct handling in `sleep.cpp` , but it's used by `RF95_DIO1` (although the RF95 setup fails _gracefully_) so you can't leave it undefined.

---
Solves #3080

### CODE REVIEW

**Comment by code8buster** [comment]
Nice and minimal.
As a point of curiosity, what effect does setting LORA_DIO1 = RADIOLIB_NC have on your variant? Does the rf95 setup still fail gracefully, or does it succeed?
RadioLib I'm wondering if that failure is RadioLib trying to attach an interrupt to that pin.

**Comment by Scarg** [comment]
Hello @code8buster!

> Nice and minimal. As a point of curiosity, what effect does setting LORA_DIO1 = RADIOLIB_NC have on your variant? Does the rf95 setup still fail gracefully, or does it succeed? RadioLib I'm wondering if that failure is RadioLib trying to attach an interrupt to that pin.

So, apparently, I got a severe case of brainfart and didn't commit the change on tlora_v2_1_16/variant.h.
My idea was to do the following:
```cpp
#ifdef TLORA_V2_1_6_TXCO
#define LORA_DIO1 32
#else
#define LORA_DIO1 33 // https://www.thethingsnetwork.org/forum/t/big-esp32-sx127x-topic-part-3/18436
#endif
````

But this is what I get in the logs:
 - if I use the stock firmware (without the TCXO support, so the one that gets Critical Fault #3)
 ```
INFO  | ??:??:?? 1 RF95 init result -16
INFO  | ??:??:?? 1 Frequency set to 906.875000
INFO  | ??:??:?? 1 Bandwidth set to 250.000000
INFO  | ??:??:?? 1 Power output set to 20
WARN  | ??:??:?? 1 Failed to find RF95 radio
```
- if I use my firmware with `#define LORA_DIO1 32` or `#define LORA_DIO1 RADIOLIB_NC` (same result)
```
INFO  | ??:??:?? 0 RF95 init result 0
INFO  | ??:??:?? 0 Frequency set to 906.875000
INFO  | ??:??:?? 0 Bandwidth set to 250.000000
INFO  | ??:??:?? 0 Power output set to 20
INFO  | ??:??:?? 0 RF95 Radio init succeeded, using RF95 radio
```
- if I use the stock firmware (without TCXO support) on a device that **does not** have TCXO
```
INFO  | ??:??:?? 1 RF95 init result 0
INFO  | ??:??:?? 1 Frequency set to 869.462524
INFO  | ??:??:?? 1 Bandwidth set to 125.000000
INFO  | ??:??:?? 1 Power output set to 20
INFO  | ??:??:?? 1 RF95 Radio init succeeded, using RF95 radio
```


Let me know what's your opinion on this.

**Comment by code8buster** [comment]
It would be better to set it as RADIOLIB_NC since 32 is not the DIO1 pin of the radio on the tcxo variant, it is the busy pin.

**Comment by Scarg** [comment]
> It would be better to set it as RADIOLIB_NC since 32 is not the DIO1 pin of the radio on the tcxo variant, it is the busy pin.

I've updated the PR with the variant.h changes using RADIOLIB_NC as suggested.

**Review by code8buster — APPROVED** [review]

**Comment by code8buster** [comment]
Added generic naming scheme per mverch on #3080 
I think it's ready to go in for 2.2.20

**Comment by Burny08** [comment]
I was about to install version 2.3.2 via the Meshtastic Web Flasher on my T-Lora 1.6 2.1, but I still get a Critical Fault #3 error. I thought the TCXO chip was supported now?

I don't have much experience, but maybe someone can check it for me please :)

Thanks!

**Pull request merged**
