### PR TITLE
Support radar sensor RCWL-9620 on i2c

### PR DESCRIPTION
**Pull request by caveman99**
Needs PR from Protos repo to compile.

### CODE REVIEW

**Comment by caveman99** [comment]
Needs PR from Protos repo to compile.

**Review by thebentern — APPROVED** [review]

**Comment by caveman99** [comment]
ARM runner still FUBAR

**Comment by thebentern** [comment]
Would be fair to say that the ARM runner needs a HAND?

**Comment by caveman99** [comment]
it needs to be put out of its misery ... :-)

**Comment by ndoo** [comment]
Hi @caveman99, I think /src/serialization/MeshPacketSerializer.cpp and possibly the nRF version of this file would need the meshtastic_PortNum_TELEMETRY_APP section updated to actually put the distance out into transmitted protobufs. 

Let me know if a separate issue should be raised.

**Comment by fifieldt** [comment]
@ndoo thanks for your detailed analysis. Please do raise a separate issue so we don't lose this important information :)

**Pull request merged**
