### PR TITLE
Remove rak4631_epaper_onrxtx variant

### PR DESCRIPTION
**Pull request by fifieldt**
Appears to be a testing variant of rak4631_epaper. Due to little information available, let's remove it for now.

### CODE REVIEW

**Comment by caveman99** [comment]
This one was instated here ... https://github.com/meshtastic/firmware/pull/2391 - what about we make a separate repository in the org to collect DIY templates/examples for variant files?

**Comment by markbirss** [comment]
@caveman99 @fifieldt 

Yes, i must just test that target again, with the current board support, also have some other wip variants for example too add e-ink and tft to wio-tracker

**Comment by markbirss** [comment]
> it would have been more beneficial to have added the support of RAK's RAK14000 E-Paper Module, which I bought assuming this variant was for, but it is not. I agree with it's removal too

"RAK's RAK14000 E-Paper" is in the rak6431_epaper variant ?

**Comment by HarukiToreda** [comment]
> > it would have been more beneficial to have added the support of RAK's RAK14000 E-Paper Module, which I bought assuming this variant was for, but it is not. I agree with it's removal too
> 
> "RAK's RAK14000 E-Paper" is in the rak6431_epaper variant ?

where can I find this variant? I only see this rak4631_eink one and it does not work. screen is attached and it does not respond with the eink display module attached.
image

**Comment by markbirss** [comment]
@HarukiToreda 

you have your flex cable connected incorrectly ? (also it best to secure the e-ink board with screws)
 
image

**Comment by HarukiToreda** [comment]
> @HarukiToreda
> 
> you have your flex cable connected correctly ? to face upward it connects to the backside of the e-ink board
> 
> (also it best to secure the e-ink board with screws)
> 
> image

attached the flex cable to the to the connector in the back and it works, thank you. This has been sitting on my drawer for months

**Pull request merged**
