### PR TITLE
Account for port number in MQTT server

### PR DESCRIPTION
**Pull request by JohnathonMohr**
The port number might also be specified in the MQTT server address. If it is, we can’t let that fail validation of a private address.

Also adding some more format validation.

~~**I still need to test this, but want to make this gap known early.**~~
✅ Tested.

### CODE REVIEW

**Comment by JohnathonMohr** [comment]
@jp-bennett @fifieldt FYI

**Review by thebentern — APPROVED** [review]

**Review by fifieldt — APPROVED** [review]
Argh, thanks for this!

**Comment by JohnathonMohr** [comment]
Any ideas why the build suddenly failed? Is it transient?

**Comment by fifieldt** [comment]
Possibly. Re-running.

**Pull request merged**
