### PR TITLE
Ignore seen phoneapi packets

### PR DESCRIPTION
**Pull request by thebentern**
Turns out some of the Phone API spam is actually replaying the same packets. This completely silences the Rate limit notification spam on my devices.

### CODE REVIEW

**Comment by GUVWAF** [comment]
Do we know why it is replaying the same packets?

**Comment by thebentern** [comment]
> Do we know why it is replaying the same packets?

No, I have been trying to figure out if it's somehow related to the push / pull system of notify and read value from characteristic or something going haywire in the bluetooth stack in iOS. I have not reproduced it on the Android side, but I have not done much testing there.

> I'm not sure if all clients actually set a packet ID or leave it 0, which would not work with this.

I know iOS is generating packet IDs, but I'll double check if Android as well.

**Comment by jp-bennett** [comment]
Or just make an exception for packets with num of 0

**Comment by thebentern** [comment]
> Or just make an exception for packets with num of 0

Easy addition. I'll whip this up

**Pull request merged**
