### PR TITLE
Update MQTT.cpp

### PR DESCRIPTION
**Pull request by arduionoGP**
Added a third valid JSON envelope to send via MQTT to device. NodeINFO to send User data that triggers User responses. The new type is "senduser".  A valid envelope looks like:
{
    "sender": "Broker",
    "type": "senduser",
    "payload": {
        "id": "!7efec08c",
        "long_name": "Meshtastic c08c",
        "short_name": "c08c",
    }
}

## Thank you for sending in a pull request, here's some tips to get started!

(Please delete all these tips and replace with your text)

- Before starting on some new big chunk of code, it it is optional but highly recommended to open an issue first
  to say "hey, I think this idea X should be implemented and I'm starting work on it. My general plan is Y, any feedback
  is appreciated." This will allow other devs to potentially save you time by not accidentially duplicating work etc...
- Please do not check in files that don't have real changes
- Please do not reformat lines that you didn't have to change the code on
- We recommend using the [Visual Studio Code](https://platformio.org/install/ide?install=vscode) editor and the 'clang-format' extension,
  because automatically follows our indentation rules and it's auto reformatting will not cause spurious changes to lines.
- If your PR fixes a bug, mention "fixes #bugnum" somewhere in your pull request description.
- If your other co-developers have comments on your PR please tweak as needed.

### CODE REVIEW

**Review by garthvh — COMMENTED** [review]
There are several fields missing
* macaddr
* hw_model
* is_licensed

**Comment by caveman99** [comment]
While this uses the same sematic as sendtext and sendposition, sending a user record is not the same thing, as it is not content but metadata. This essentially allows to inject 'fake' or 'phantom' devices into the mesh. Can you elaborate a bit on the use-case, i am hesitant to support that.

**Comment by garthvh** [comment]
> While this uses the same sematic as sendtext and sendposition, sending a user record is not the same thing, as it is not content but metadata. This essentially allows to inject 'fake' or 'phantom' devices into the mesh. Can you elaborate a bit on the use-case, i am hesitant to support that.

Good point, there is also never a case where a user exists separate from a node info on the mesh, sending in user packets is likely to break apps

**Comment by arduionoGP** [comment]
I left those fields out on the publish side because you also left them out in the decoding side code (the "Case" statements toward the end) and I wanted the code to look consistent.

For a use case, consider two geographically separate meshes, each with their own gateway to their own mqtt server. (Each MQTT server allows for the store/forward functionality which is built into MQTT.) The two servers can only intermittently communicate because internet is down and sat com is not continuous. Mobile assets in both meshes can come and go depending on range and need to be geo-plotted and able to send messages bridging both areas. For transparent bridging it seemed to me that this would require text, pos, and user portnums to both upload and download.

**Comment by garthvh** [comment]
User never exists without a node, why would mqtt need to send one that is not part of a real node?

**Comment by garthvh** [comment]
This will not do anything, there is no routing for a user only packet

**Comment by caveman99** [comment]
Just a few musings on this. the JSON facility is meant to get data from the mesh easily, and provide a few rudimentary functions to send data to it. Bridging was never the scope of JSON/MQTT. The other MQTT-Topic transports all neccessary protobufs to do a bridging setup. If you ant to do more fancy stuff than feed data into NodeRed, for the love of god use the protobufs!

**Pull request closed without merging**
