### PR TITLE
Add support for ignoring nodes with `is_ignored` field in NodeInfo

### PR DESCRIPTION
**Pull request by mdesmedt**
This adds the `is_ignored` field to `NodeInfo` structs. It functions similarly to the existing `is_favorite` field. The field gets checked in `Router::perhapsHandleReceived` and when set the packet is dropped.

This will enable clients to configure their node to drop packets from other nodes. Much in the same way as `LoRaConfig.ignore_incoming` but without being limited to 3 entries.

This change depends on the protobuf changes in PR https://github.com/meshtastic/protobufs/pull/621

Implements my feature request here: https://github.com/meshtastic/firmware/issues/5297

### CODE REVIEW

**Comment by thebentern** [comment]
Really great solution to this issue. I think we'll probably end up deprecating the ignore_incoming after this gets integrated.

**Review by thebentern — APPROVED** [review]

**Review by GUVWAF — COMMENTED** [review]
Looks good, although maybe we should already have it migrate from the `ignore_incoming` array to this bool? Then we won't be sticking forever with two possible configurations.

**Comment by GUVWAF** [comment]
Hmm, now that I think twice about this, I think this would be non-ideal, because usually you also don't want ignored nodes in your node list. However, if you delete the node, it will be un-ignored.

**Comment by ianmcorvidae** [comment]
I suppose that with the node ignored you probably also won't see updates from it, ultimately making its last-seen time later and later and eventually pushing it out of nodedb, which would then lose the ignored state. We'd need to treat this like favorites and prioritize keeping them around, I guess, which is admittedly a little weird.

Would it be nuts to expand the nodedb by the number of ignored nodes, but trim as much information out of the ignored node entries as possible so it isn't space-prohibitive? I guess it really only needs to hold onto the nodenum and the is_ignored flag.

**Comment by mdesmedt** [comment]
> Hmm, now that I think twice about this, I think this would be non-ideal, because usually you also don't want ignored nodes in your node list. However, if you delete the node, it will be un-ignored.

Yes, although first I thought having the `is_ignored` field in the NodeDB is primarily a UI consideration (the apps could choose to list ignored nodes in a different part of the UI if desired), perhaps using the NodeDB is actually not ideal.

Maintaining a dynamically sized uint32 array shouldn't be that difficult. Now that I understand the project a little better, instead of this approach, perhaps it should just be a new `repeated uint32` field in `DeviceState`, like `node_db_lite` is.

The `set_ignored_node/remove_ignored_node` admin messages can still be used. All that's needed is a way to query the list over proto. Maybe something as straightforward as a pair of get/response admin messages entries for A. the size of the ignore list and B. a query by index? Let me know if you would like me to try to code this approach instead, and I can submit a different PR.

**Comment by thebentern** [comment]
I think the nodes you ignore being in the nodedb to show up in the list is actually a feature for apps to build around rather than a drawback. You can actually see who you've blocked on your mesh and remove it if you made a mistake. Apps can present this like blocking features in messaging clients. Keep in mind this probably won't get used extensively. We identified that 3 is not enough, but I doubt most meshes will ever block more than possibly 10 nodes.

**Comment by GUVWAF** [comment]
Okay, that's fair, although the apps would then need to disable the option to remove it when it's ignored, and we'd still need to avoid cycling them out of the NodeDB.

**Comment by thebentern** [comment]
> Okay, that's fair, although the apps would then need to disable the option to remove it when it's ignored, and we'd still need to avoid cycling them out of the NodeDB.

Exactly. We want to treat them as favorites in terms of the devices not pushing them out when new nodes roll in and @garthvh @andrekir should be able to guard against a user deleting them after they are ignored. Assuming we could do something like force a user to unignore the node before removing them? I think that would go a long way at preventing confusion.

**Comment by thebentern** [comment]
I have pushed the change to no longer consider is_ignored a _boring_ node. :-)

**Review by GUVWAF — APPROVED** [review]

**Pull request merged**
