### PR TITLE
Finish powermon/powerstress

### PR DESCRIPTION
**Pull request by geeksville**
This is the final changes for the powermon/powerstress stuff.  Sorry for the long list of CLs, but I have been merging from master for a while so hard to rebase/collapse the various non merge changes into a single CL.

There are three main changes:
* Implement the PowerStress class so that the python code can ask the unit under test (UUT) to transition through various modes while it measures the power consumed by the board.  (This class is not used in normal operation)
* Have various places that are doing power changing things (turning on power rails, changing radio modes etc...) call hooks on the powermon singleton to indicate those operations are happening.  Those hooks emit a structured string to the log file output.  This class is tiny so I left it on by default.
* Add GpioTransformer/GpioPin classes which I will soon use for decreasing Heltec tracker power consumption (by managing the dedicated screen+gps power regulator more conservatively).  Currently this class is only used for the power led (so that the led can be controlled by PowerStress - and then we eventually calibrate/detect from the python side that the bench power measurement is working).

Any feedback/comments would be appreciated!  (sorry for the delay - I took an extra week off from programming but now back at it)

For #4136

### CODE REVIEW

**Review by thebentern — APPROVED** [review]

**Review by todd-herbert — CHANGES_REQUESTED** [review]
Just a heads up that I built this for T-Beam V1.2 but it's crashing at boot.
```
0x40152b0f: do_global_ctors at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/startup.c:201
0x40152b0f: start_cpu0_default at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/startup.c:449
0x40083aad: call_start_cpu0 at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/port/cpu_start.c:687
```

Not sure if it's this PR or something unrelated from master. Will keep building stuff here and see if anything turns up.

**Comment by geeksville** [comment]
@todd-herbert your note prompted me to try it on a tbeam!  You are correct.  I'll take a look!

**Comment by geeksville** [comment]
thanks @todd-herbert - I think ready to go (again ;-) )

**Review by todd-herbert — APPROVED** [review]
Looks like you got it!

**Comment by geeksville** [comment]
thanks @todd-herbert.  Updated wrt master and I think ready to merge.  cool @thebentern?  (I'm lazy and eager to not keep updating wrt master.  heh)

**Comment by thebentern** [comment]
Sounds good. Merging :D

**Pull request merged**
