### PR TITLE
Add Heltec Mesh Node T114 No Screen board definition

### PR DESCRIPTION
**Pull request by Heltec-Aaron-Lee**
Add Heltec Mesh Node T114 No Screen board definition.

The default BlueTooth connection pin code is `123456`

### CODE REVIEW

**Comment by lyusupov** [comment]
Aaron, what's up with Heltec T114 **V1** replacement program ?

I've made a request via AliExpress on October 13th and the Hectec Seles personnel responded that the request was accepted.
Today is December 3rd, few days before completion of 2 month period, but the replacement (1 piece of T114 V2) is still NOT shipped out.

**Comment by mverch67** [comment]
IMO this PR is a bit like shooting sparrows with cannons. There is no need for another variant as it is likely that the variant could be requested at runtime. The ST7789 display driver supports SDA+DC readings of the driver ID. 

I did run a slightly modified sketch of [this](https://github.com/prenticedavid/ST7789_kbv/blob/master/examples/ST7789_readreg_diag/ST7789_readreg_diag.ino) with the heltec T114 and got the following result:

`read reg(4):  ID = 0x8181B3`

**Comment by Heltec-Aaron-Lee** [comment]
@mverch67 

Due to the inability of the screenless version of T114 to display the Bluetooth connection pin code on the display, this update has been submitted in response to numerous user requests.

**Comment by Heltec-Aaron-Lee** [comment]
Hi @lyusupov 

Very sorry about that. I just confirmed with my colleague that all reissues will be completed within this week.

**Comment by thebentern** [comment]
> Due to the inability of the screenless version of T114 to display the Bluetooth connection pin code on the display, this update has been submitted in response to numerous user requests.

I believe Manuel is suggesting we might be able to probe those registers and detect presence of the display or not to set the Bluetooth pin mode default config.

**Comment by Heltec-Aaron-Lee** [comment]
Haha @thebentern 

Indeed verification via register is the best way, but adding a new hardware model can quickly solve many of the current user problems, and our upcoming `nRF+SX1262` module can also use this model, making it convenient for more people to DIY their own Meshtastic hardware

**Comment by mverch67** [comment]
@Heltec-Aaron-Lee 
Haha, no objections to leave this PR open for users who want a quick-and-dirty solution and use it for their DIY compilation of this firmware for the no_screen variant or the upcoming nrf+SX162 module.

I compared the code with the existing variant and found only one single change:
image

Copy and paste of the entire variant because of this single change obviously doesn't make much sense and will also confuse the user with so many variants. So I think we'd need another PR that queries the ST7789 driver at runtime and sets a corresponding flag to set the initial bluetooth password.

**Comment by thebentern** [comment]
We could also just create a new environment target in PIO with no new HW_MODEL and define the flags in the ini instead of the variant, if the intent is to have a variant without a screen which is more DIY. Presumably a user could add an I2C based oled display as well

**Pull request closed without merging**
