### PR TITLE
Reply to Repeater in DeviceTelemetry module

### PR DESCRIPTION
**Pull request by thebentern**

### CODE REVIEW

**Comment by GUVWAF** [comment]
How will one be able to select the repeater as destination, since it is not in the NodeDB?

Also currently upon receiving the response from the repeater, the other nodes will send out their NodeInfo and ask for a response from the repeater (because they don't have it in their NodeDB), but it will not be able to answer.

**Comment by thebentern** [comment]
That is a good point. I forgot that sending with a --dest tries to pull from NodeDB. I'm not sure how this will behave with a forged request, but I intend to experiment with it in the C# client, if nothing else to satisfy my own curiosity. :-) 
Any ideas for an alternative? Almost wondering if we need some sort of heartbeat / status module in the long term. Traceroute lets you know it's still alive, but folks want something to know the repeater isn't about to have a dead battery in solar installations especially.

**Comment by GUVWAF** [comment]
The default broadcast of the DeviceTelemetry is actually like a heartbeat/status module, right? I definitely see why getting the battery status is useful and being able to request it seems like a nice approach in order to still have the advantage of a repeater not contributing to traffic load. However, currently the only way to make this possible is when the repeater also has the NodeInfoModule and thus it would be stored in each node’s NodeDB.

Actually the only thing you need to know is its NodeNum, but letting users write that down sounds a bit cumbersome :sweat_smile: 
Maybe we could just use the broadcast address and let only repeaters respond to that?

Not sure how this would work client-wise, because it doesn’t know the node that responded. Maybe something like “_A repeater with NodeNum x responded with: …_“

**Comment by thebentern** [comment]
Tested in C# client (WIP) and seems to work
`Sent: { "packet": { "to": 1734053744, "decoded": { "portnum": "TELEMETRY_APP", "payload": "EgA=", "wantResponse": true }, "id": 4294967295, "hopLimit": 3, "wantAck": true } }
Payload decoded: { "deviceMetrics": { } }
Received: { "queueStatus": { "free": 14, "maxlen": 16, "meshPacketId": 840478738 } }
Received packet from device: { "queueStatus": { "free": 14, "maxlen": 16, "meshPacketId": 840478738 } }
Received: { "packet": { "from": 1734053744, "to": 3693202693, "decoded": { "portnum": "TELEMETRY_APP", "payload": "DR4AAAASDAhlFUSLiEAdagNdPw==", "requestId": 4294967295 }, "id": 1465824668, "rxSnr": 5.75, "hopLimit": 3, "wantAck": true, "rxRssi": -8 } }
Received packet from device: { "packet": { "from": 1734053744, "to": 3693202693, "decoded": { "portnum": "TELEMETRY_APP", "payload": "DR4AAAASDAhlFUSLiEAdagNdPw==", "requestId": 4294967295 }, "id": 1465824668, "rxSnr": 5.75, "hopLimit": 3, "wantAck": true, "rxRssi": -8 } }
{ "batteryLevel": 101, "voltage": 4.267, "channelUtilization": 0.86333334 }`


`DEBUG | ??:??:?? 30 [RadioIf] (bw=250, sf=11, cr=4/8) packet symLen=8 ms, payloadSize=24, time 518 ms
DEBUG | ??:??:?? 30 [RadioIf] Lora RX (id=0xffffffff fr=0x05 to=0x70, WantAck=1, HopLim=3 Ch=0x8 encrypted rxSNR=6 rxRSSI=-7)
DEBUG | ??:??:?? 30 [RadioIf] AirTime - Packet received : 518ms
DEBUG | ??:??:?? 30 [Router] Add packet record (id=0xffffffff fr=0x05 to=0x70, WantAck=1, HopLim=3 Ch=0x8 encrypted rxSNR=6 rxRSSI=-7)
DEBUG | ??:??:?? 30 [Router] Using channel 0 (hash 0x8)
DEBUG | ??:??:?? 30 [Router] Expanding short PSK #1
DEBUG | ??:??:?? 30 [Router] Using AES128 key!
DEBUG | ??:??:?? 30 [Router] nRF52 encrypt fr=dc21cd05, num=ffffffff, numBytes=8!
DEBUG | ??:??:?? 30 [Router] decoded message (id=0xffffffff fr=0x05 to=0x70, WantAck=1, HopLim=3 Ch=0x0 Portnum=67 WANTRESP rxSNR=6 rxRSSI=-7)
DEBUG | ??:??:?? 30 [Router] handleReceived(REMOTE) (id=0xffffffff fr=0x05 to=0x70, WantAck=1, HopLim=3 Ch=0x0 Portnum=67 WANTRESP rxSNR=6 rxRSSI=-7)
DEBUG | ??:??:?? 30 [Router] Module 'DeviceTelemetry' wantsPacket=1
INFO  | ??:??:?? 30 [Router] Received DeviceTelemetry from=0xdc21cd05, id=0xffffffff, portnum=67, payloadlen=2
INFO  | ??:??:?? 30 [Router] Device telemetry replying to request
DEBUG | ??:??:?? 30 [Router] Initial packet id 1465824666, numPacketId 4294967295
INFO  | ??:??:?? 30 [Router] Asked module 'DeviceTelemetry' to send a response
DEBUG | ??:??:?? 30 [Router] Module 'routing' wantsPacket=1
INFO  | ??:??:?? 30 [Router] Received routing from=0xdc21cd05, id=0xffffffff, portnum=67, payloadlen=2
DEBUG | ??:??:?? 30 [Router] Routing sniffing (id=0xffffffff fr=0x05 to=0x70, WantAck=1, HopLim=3 Ch=0x0 Portnum=67 WANTRESP rxSNR=6 rxRSSI=-7)
DEBUG | ??:??:?? 30 [Router] Delivering rx packet (id=0xffffffff fr=0x05 to=0x70, WantAck=1, HopLim=3 Ch=0x0 Portnum=67 WANTRESP rxSNR=6 rxRSSI=-7)
DEBUG | ??:??:?? 30 [Router] Update DB node 0xdc21cd05, rx_time=0, channel=0
DEBUG | ??:??:?? 30 [Router] Forwarding to phone (id=0xffffffff fr=0x05 to=0x70, WantAck=1, HopLim=3 Ch=0x0 Portnum=67 WANTRESP rxSNR=6 rxRSSI=-7)
DEBUG | ??:??:?? 30 [Router] Module 'routing' considered
DEBUG | ??:??:?? 30 [Router] Sending response (id=0x575eb59c fr=0x70 to=0x05, WantAck=1, HopLim=3 Ch=0x0 Portnum=67 requestId=ffffffff priority=70)
DEBUG | ??:??:?? 30 [Router] Update DB node 0x675b8f70, rx_time=0, channel=0
DEBUG | ??:??:?? 30 [Router] localSend to channel 0
DEBUG | ??:??:?? 30 [Router] Add packet record (id=0x575eb59c fr=0x70 to=0x05, WantAck=1, HopLim=3 Ch=0x0 Portnum=67 requestId=ffffffff priority=70)
DEBUG | ??:??:?? 30 [Router] Expanding short PSK #1
DEBUG | ??:??:?? 30 [Router] Using AES128 key!
DEBUG | ??:??:?? 30 [Router] nRF52 encrypt fr=675b8f70, num=575eb59c, numBytes=28!
DEBUG | ??:??:?? 30 [Router] enqueuing for send (id=0x575eb59c fr=0x70 to=0x05, WantAck=1, HopLim=3 Ch=0x8 encrypted priority=70)
DEBUG | ??:??:?? 30 [Router] txGood=0,rxGood=1,rxBad=0`

**Pull request merged**
