### PR TITLE
Attempts at getting the Heltec Wireless Paper eink operational

### PR DESCRIPTION
**Pull request by thebentern**
@markbirss here are my logs. Nothing suspicious:

INFO  | ??:??:?? 2 Doing EInk init
INFO  | ??:??:?? 2 Turning on screen
DEBUG | ??:??:?? 2 Updating E-Paper... done
DEBUG | ??:??:?? 2 Module wants a UI Frame
DEBUG | ??:??:?? 2 Module wants a UI Frame
WARN  | ??:??:?? 2 SX126xInterface(cs=8, irq=14, rst=12, busy=13)
INFO  | ??:??:?? 2 Starting meshradio init...
DEBUG | ??:??:?? 2 (bw=250, sf=11, cr=4/8) packet symLen=8 ms, payloadSize=0, time 231 ms
DEBUG | ??:??:?? 2 (bw=250, sf=11, cr=4/8) packet symLen=8 ms, payloadSize=253, time 3246 ms
INFO  | ??:??:?? 2 Radio freq=906.875, config.lora.frequency_offset=0.000
INFO  | ??:??:?? 2 Set radio: region=UNSET, name=LongFast, config=0, ch=19, power=30
INFO  | ??:??:?? 2 Radio myRegion->freqStart -> myRegion->freqEnd: 902.000000 -> 928.000000 (26.000000 mhz)
INFO  | ??:??:?? 2 Radio myRegion->numChannels: 104 x 250.000kHz
INFO  | ??:??:?? 2 Radio channel_num: 20
INFO  | ??:??:?? 2 Radio frequency: 906.875000
INFO  | ??:??:?? 2 Slot time: 42 msec
INFO  | ??:??:?? 2 Set radio: final power level=22
INFO  | ??:??:?? 2 SX126x init result 0
INFO  | ??:??:?? 2 Frequency set to 906.875000
INFO  | ??:??:?? 2 Bandwidth set to 250.000000
INFO  | ??:??:?? 2 Power output set to 22
DEBUG | ??:??:?? 2 Current limit set to 140.000000
DEBUG | ??:??:?? 2 Current limit set result 0
DEBUG | ??:??:?? 2 SX126X_E22 mode enabled. Setting DIO2 as RF Switch
INFO  | ??:??:?? 2 Set Rx Power Saving Gain mode; result: 0
INFO  | ??:??:?? 2 SX1262 Radio init succeeded, using SX1262 radio
INFO  | ??:??:?? 2 Not using WIFI
DEBUG | ??:??:?? 2 (bw=250, sf=11, cr=4/8) packet symLen=8 ms, payloadSize=237, time 3057 ms
DEBUG | ??:??:?? 2 LoRA bitrate = 77.526985 bytes / sec
INFO  | ??:??:?? 2 PowerFSM init, USB power=1
DEBUG | ??:??:?? 2 Enter state: BOOT
[  2565][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 6 = 80 Mhz, APB: 80000000 Hz
DEBUG | ??:??:?? 2 [Power] Battery: usbPower=0, isCharging=0, batMv=0, batPct=0
DEBUG | ??:??:?? 2 [Screen] Screen: Started...
INFO  | ??:??:?? 2 [RangeTestModule] Range Test Module - Disabled
DEBUG | ??:??:?? 3 [Screen] Updating E-Paper... done
DEBUG | ??:??:?? 4 [Screen] Updating E-Paper... done
DEBUG | ??:??:?? 5 [PowerFSM] Enter state: POWER
INFO  | ??:??:?? 5 [PowerFSM] Initialise the NimBLE bluetooth module
DEBUG | ??:??:?? 6 [Screen] Updating E-Paper... done
INFO  | ??:??:?? 7 [Screen] Done with boot screen...
DEBUG | ??:??:?? 7 [Screen] showing standard frames
DEBUG | ??:??:?? 7 [Screen] Showing 0 module frames
DEBUG | ??:??:?? 7 [Screen] Total frame count: 83
DEBUG | ??:??:?? 7 [Screen] Added modules.  numframes: 0
DEBUG | ??:??:?? 7 [Screen] Finished building frames. numframes: 2
DEBUG | ??:??:?? 7 [Screen] Updating E-Paper... done
DEBUG | ??:??:?? 22 [Power] Battery: usbPower=0, isCharging=0, batMv=0, batPct=0

It's almost like the eink is just stuck. It still has the Heltec logo on it.

### CODE REVIEW

**Comment by markbirss** [comment]
@thebentern 

The Debug output for E-Paper should show values in ms which was spent on SPI bus f it is initialised correctly
`DEBUG | 12:38:08 3 Updating E-Paper... _PowerOn : 148996
_Update_Full : 931000
_Update_Part : 327000
_PowerOff : 63000
done`

**Comment by ixt** [comment]
@thebentern I solved this on the fork here: https://github.com/ixt/firmware/tree/heltec-paper
and opened a pr to the GxEPD2 fork Meshtastic manages. 

My guess is a combination of things, depending on which wireless paper you have. Mine is labeled v1.1 with the green tab on the screen protector. I have two of them, and I'm assuming this is the most common? 

I couldnt find any documentation regarding the actual display but through banging my head enough times and learning more about epaper than I wish I knew, I found the right commands to get things to display. Regarding what it seemed like you were trying to solve with the SPI, GxEPD2 just doesnt like being given a new bus it seems, and you need to pull Vext low to turn the display on in the first place it seems. But it's not clear, all I know is it worked. 

The display itself I think is running a different variant of a UltraChip controller than is listed everywhere, I took most of the stuff from various examples and systematically checked what helped and didnt help, after cross referencing the closest 3 EPD data sheets I could find, if they had them at all. 

Something with the drawing messes up the final row of pixels, right now I have it blank them out. I might revisit them, but for the sake of the bottom pixel of the dot I'm not sure they will be missed. I made a few attempts at it to no luck, I might revisit later and left my most promising attempt commented out. 

v1 uses a different range of commands too, I havent got one to test, but I'm guessing it'll be a lot closer to the other GxEPD2 supporting displays.

**Comment by markbirss** [comment]
@ixt 

> My guess is a combination of things, depending on which wireless paper you have. Mine is labeled v1.1 with the green tab on the screen protector. I have two of them, and I'm assuming this is the most common

The silkscreen printing on the e-ink flex cable itself provides better way to identify the actual e-ink display being used not the color of the tab on the screen protector

e.g

`//#define GxEPD2_DRIVER_CLASS GxEPD2_213     // GDE0213B1   122x250, IL3895, (HINK-E0213-G01), phased out

//#define GxEPD2_DRIVER_CLASS GxEPD2_213_B72 // GDEH0213B72 122x250, SSD1675A (IL3897), (HINK-E0213A22-A0 SLH1852)

//#define GxEPD2_DRIVER_CLASS GxEPD2_213_B73 // GDEH0213B73 122x250, SSD1675B, (HINK-E0213A22-A0 SLH1914)

//#define GxEPD2_DRIVER_CLASS GxEPD2_213_B74 // GDEM0213B74 122x250, SSD1680, FPC-7528B)

//#define GxEPD2_DRIVER_CLASS GxEPD2_213_BN // DEPG0213BN  122x250, SSD1680, (FPC-7528B), TTGO T5 V2.4.1, V2.3.1

//#define GxEPD2_DRIVER_CLASS GxEPD2_213_GDEY0213B74 // GDEY0213B74 122x250, SSD1680, (FPC-A002 20.04.08)`


> Something with the drawing messes up the final row of pixels,

This is due to a mismatch in GxEPD2 support for the display resolution y dimension not being 128 but 122 - you can move up the dots by 6 pixels in the oled lib and use 128 for y but it will affect all displays

**Comment by ixt** [comment]
@markbirss The colour is what is mentioned in heltec's documentation here: https://docs.heltec.org/en/node/esp32/hardware_update_log.html 

And I am aware its because of the mismatched resolution, I believe it can be fixed. But it might be above my understanding for now and is more trouble than its worth for our use. I think it would be better to fix it in the GxEPD2 fork than mess with the OLEDLibrary and/or add more IFDEFs but now in the UI stuff.

**Comment by markbirss** [comment]
@ixt 

Some of Heltec e-ink module here identified by Flex Connector Label (so we need to outside view)

image

https://github.com/todd-herbert/heltec-eink-modules

https://github.com/todd-herbert/heltec-eink-modules/blob/main/docs/FlexConnector/declare_by_flex.md

**Comment by ixt** [comment]
@markbirss no code on outside

**Pull request closed without merging**
