### PR TITLE
Adds ASCII log option needed by portudino

### PR DESCRIPTION
**Pull request by charlieh0tel**
Adds ASCII log option to prevent control characters going into syslog. 
This is needed to get reasonable logs for portudino.

### CODE REVIEW

**Comment by charlieh0tel** [comment]
PTAL.

**Comment by jp-bennett** [comment]
> PTAL.

I'll give it a closer look and a test run, but looking good.

**Comment by jp-bennett** [comment]
@charlieh0tel One last thing. Can you add an AsciiLogs entry to bin/config-dist.yaml, commented out by default?

**Comment by charlieh0tel** [comment]
do i need to rebase this?

**Comment by jp-bennett** [comment]
> do i need to rebase this?

Nope, this looks good. I'll do a squash and merge once CI finishes.

**Pull request merged**
