### PR TITLE
Add QueueStatus sending to the firmware

### LINKED ISSUE #1819: when outgoing TX Queue is full messages are simple dropped without notification
### Category

Other

### Hardware

Not Applicable

### Firmware Version

1.3.46

### Description

An attempt to send more than 16 messages discards some of them silently.

I propose to add a QueueStatus message to FromRadio that will notify host with the status of the TX Queue as well as latest attempt to queue a message.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by pavelb-techspark**
# Add TX Queue Status messages

This set of PRs adds and processes special QueueStatus protobuf as a part of data sent FromRadio. The QueueStatus proto is the following (https://github.com/meshtastic/Meshtastic-protobufs/pull/215):
```proto3
message QueueStatus {
  /* Last attempt to queue status, ErrorCode */
  int32 res = 1;

  /* Free entries in the outgoing queue */
  uint32 free = 2;

  /* Maximum entries in the outgoing queue */
  uint32 maxlen = 3;

  /* What was mesh packet id that generated this response? */
  uint32 mesh_packet_id = 4;
}
```

Upon reception of the every MeshPacket protobuf the code in `MeshService::sendToMesh` combines status of the attempt to queue the message with queue status requested from the `RadioInterface`, marking it with the `MeshPacket.id` that was attempted to be queued.

Additionally, when queue status changes from completely busy (free == 0) to something else a QueueStatus packet is sent to notify the app that there is now a free space in queue. Here is the complete description of all the possible QueueStatus variants:

1. `res = 0, free = n, maxlen = N, mesh_packet_id != 0`
    Means that latest message with `MeshPacket.id = mesh_packet_id` was queued successfully and there is still `n` places available in the RadioInterface TX queue.
    
2. `res != 0, free = 0, maxlen = N, mesh_packet_id != 0`

   TX Queue could not accommodate the latest `mesh_packet_id` message. It must be resent to the radio later.
   
3. `res = 0, free = n != 0, maxlen = N, mesh_packet_id = 0`

   Radio just sent a single packet and now there is a free place in the TX queue. App can now send `n` packets that previously returned `res != 0` to the queue.

It is advised that application keeps outgoing queue of its own, removing packets with `MeshPacket.id == mesh_packet_id` on `res = 0`  `QueueStatus`, and placing sent packets at the end of the queue.

Sample implementation of this logic can be found here: https://github.com/meshtastic/Meshtastic-python/pull/386 

Fixes #1819

### CODE REVIEW

**Review by caveman99 — CHANGES_REQUESTED** [review]
Also please remove ALL files under 'generated' from this PR; as they will be replaced on the next proto update anyway.

**Comment by caveman99** [comment]
the cppcheck high level errors must be adressed too before we can merge.

`src/mesh      144       1        0`

**Comment by pavelb-techspark** [comment]
> Also please remove ALL files under 'generated' from this PR; as they will be replaced on the next proto update anyway.

Done.

**Comment by thebentern** [comment]
I really like this idea of providing more information over the PhoneAPI about the status of the outgoing queue, but alas this is change is happening at a point in the project too close our November timeline of releasing 2.0. It would require all of the consuming apps to account for the new FromRadio packets which are intrinsic and potentially break backwards compatibility with communicating to devices with previous firmware builds on some platforms. 
All of that to say, I want to keep this PR open, because I do really like the idea and I'd like to try to incorporate it some time after we go live with 2.0.

**Comment by pavelb-techspark** [comment]
@thebentern thanks for the response!

As per my understanding any app that silently ignores unknown types of Protobufs will simple continue working as it was. Compatibility between QueueStatus-aware apps and older firmwares can also be achieved by checking for arrival of the QueueStatus packets at least once, and code in `loop` will ensure that (somehow unclear though).

I agree that introducing such a change that close to the release is a bad idea. Looking forward for the post-release days and would be glad to help introduce changes to the Android app and further!

**Comment by pavelb-techspark** [comment]
@thebentern may we get some traction here? What is needed to merge this?

**Comment by D4rk4** [comment]
Any progress with this?

**Comment by D4rk4** [comment]
@pavelb-techspark please fix checks

**Comment by pavelb-techspark** [comment]
@D4rk4 the thing is ``src/mesh/generated`` are updated from the protobufs pipeline automatically, so checks will fail until protobufs are merged or I have a commit that updates them, which is against rules as per https://github.com/meshtastic/firmware/pull/1820#pullrequestreview-1145705446 .

I updated generated files manually just to have a firmware to test.

**Comment by sachaw** [comment]
I'll see if I can get this one moving along

**Comment by sachaw** [comment]
@pavelb-techspark I can merge the protobufs, there's just one outstanding question over there: https://github.com/meshtastic/protobufs/pull/215
@mc-hamster asked "Why is res a signed value?"
as soon as that's resolved, I'll merge this in.

**Comment by sachaw** [comment]
Also, @pavelb-techspark can you please change the target branch to develop:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Review by caveman99 — APPROVED** [review]

**Pull request merged**
