### PR TITLE
Fix sending duplicate packets to PhoneAPI/MQTT

### PR DESCRIPTION
**Pull request by GUVWAF**
Accidentally introduced with #5232.

When receiving repeated packets due to dropped ACKs/replies, we should re-do any routing or sending ACK/replies, but we shouldn’t resend it to the PhoneAPI or MQTT. 

To check this, I moved the PacketHistory to the Router class (which is needed for #2856 anyway).

### CODE REVIEW

**Review by thebentern — APPROVED** [review]

**Review by fifieldt — APPROVED** [review]

**Comment by GUVWAF** [comment]
@thebentern Just found that in some cases this actually causes it to not send to the PhoneAPI when it actually should. Will try to find a better fix...

**Comment by VigibotDev** [comment]
Thanks for solving. Going test :)

**Comment by VigibotDev** [comment]
Testing 2.5.13 for duplicate message it's not ok for now. Easy to reproduce for me feel free ask more testing.

Screenshot_20241114_180949_Meshtastic
Screenshot_20241114_180838_Meshtastic

**Comment by VigibotDev** [comment]
OK I must update the other side also because it can receive twice also

**Comment by VigibotDev** [comment]
Solved for me :)
Screenshot_20241114_183511_Meshtastic
Screenshot_20241114_183834_Meshtastic

**Pull request merged**
