### PR TITLE
Add CircutMess Chatter 2 

### PR DESCRIPTION
**Pull request by GPSFan**
Add the CircuitMess Chatter 2.
This is almost a plug & play addition with the exception of the LLCC68 Lora module which is crippled wrt Meshtastic, It only allows interoperability with the standard preset of Medium-Slow. However it is possible to replace the Lora module with a Heltec RA-62 which is "almost" pin compatible. It requires one trace cut to remove the connection between Pin 26 of the ESP-32 module and Pin 5 of the Lora module, and a jumper to connect Pin 26 of the ESP-32 module to Pin 10 of the RA-62.
This allows full operation of the Chatter 2 with all of Meshtastics's Presets.
What works with or without the Lora module replacement:
The display.
The Beeper, although it is not too loud.
There is a wake functionality using the lower right button on the Chatter 2 keyboard.
There is GPS/GNSS capability using the 4 pin extension port of the Chatter 2, GPS is enabled by default in varient.h
GPS software power down.
External LORA Antenna capability is provided by the RA-62's UFL connector,
What doesn't work:
The remainder of the keyboard, A usage model needs to be developed and code written to scan and decode functionality.
Display flip.
GPS power off.

### CODE REVIEW

**Comment by code8buster** [comment]
To be clear what your variant.h is written to support:
Is it written to support your particular modification, with the Heltec RA62 module?
Are the correct GPIO assignments present but commented, if one wished to use the Chatter's stock LLCC68?

**Comment by GPSFan** [comment]
Thanks for spotting that. The committed variant.h will support  the RA-62. I intended to have both USE_LLCC68 and USE_SX1262 uncommented when I did the PR, but forgot to remove the // ;>P
The Busy pin of the LLCC68 and the Busy pin of the SX1262 are on different pins of the module so my cut & jumper will allow either to work if I hadn't forgotten to remove the "//". My bad.
The Busy signal from the esp32 is on IO4 which matches the original trace for the LLCC68 and with the cut & jumper works for the SX1262.
So I need to amend something to get rid of that pesky //.
I have used the same code with the original LLCC68 in place and it works ok except for the limitation to Medium-Slow.

**Comment by GPSFan** [comment]
Fixed the commented out define for the LLCC68

**Comment by GPSFan** [comment]
Try again...

**Comment by code8buster** [comment]
Now once we pull it in, a binary should be built for all the patient Chatter users to test out.

**Review by code8buster — APPROVED** [review]

**Review by thebentern — APPROVED** [review]

**Comment by ashdavely** [comment]
I tried to flash one of my unmodified chatter2 devices with 2.2.20alpha using Chrome - it installed but nothing shows on the screen. This probably isn't the place to ask about this but I am wondering what steps you took to flash or if you had to do anything different?

**Comment by GPSFan** [comment]
Here is fine.
You are the first to try it since I modified mine.
Can you connect via bluetooth?
Yours is a Chatter 2 correct? the original Chatter is a different animal and probably won't work.

**Comment by GPSFan** [comment]
I flashed mine via Platformio, once I started doing development work.

**Comment by ashdavely** [comment]
> I flashed mine via Platformio, once I started doing development work.

It's identical to the pictures in the request

> Here is fine. You are the first to try it since I modified mine. Can you connect via bluetooth? Yours is a Chatter 2 correct? the original Chatter is a different animal and probably won't work.

Definitely a Chatter2 - its identical to the pics in the request to add thread.

I am powering it with 3 AAA batteries as it came. I'm probably not the best person to test this as I am a new ham and this is my first exposure to meshtastic. Not new to ESP32 devices though.

**Comment by GPSFan** [comment]
Did you use the web flasher?

**Comment by ashdavely** [comment]
> Did you use the web flasher?

Yes. flasher.meshtastic.org with chrome.

**Comment by GPSFan** [comment]
And what device did you choose as the target? I just tried to do it and couldn't find the Chatter 2, maybe I missed something...

**Comment by ashdavely** [comment]
> And what device did you choose as the target? I just tried to do it and couldn't find the Chatter 2, maybe I missed something...

I picked t-beam then selected the serial port when asked. There is no chatter2 option.

**Comment by GPSFan** [comment]
Bad move, t-beam has very different pinouts for the esp32 than the Chatter 2.

**Comment by GPSFan** [comment]
Try downloading the 2.2.20  and follow the instructions to flash vie the CLI using esptool.
You running Linux, Mac oe Windoze?

**Comment by ashdavely** [comment]
I also reflashed it with heltec ht62.  It flashed and could still connect over usb.

**Comment by GPSFan** [comment]
Nothing but the Chatter 2 varient will work because of the very diferent pinnouts, I have no clue as to why there is no Chatter 2 selection on the web flasher.

**Comment by GPSFan** [comment]
The Chatter 2 hasn't made it into the web flasher's resources.ts file yet, that's why it doesn't show up yet.

**Comment by ashdavely** [comment]
i was able to flash it the hard way using platformio using some instructions on the meshtastic site. seems to be working. why does the screen say unpowered yet shows a battery status?

**Comment by GPSFan** [comment]
The A/D is connected to the battery, so it can tell it's voltage. Unpowered is an artifact of what the voltage is WRT the threshold settings in varient.h

**Comment by GPSFan** [comment]
The wakeup button works, barely, probably a result of running at only 80MHz.

**Comment by sirkleson** [comment]
@ashdavely can you provide some links? I am wanting to get this going as well. Thanks in advance..

**Comment by ashdavely** [comment]
> @ashdavely can you provide some links? I am wanting to get this going as well. Thanks in advance..

I started with the first 2 sections here in the link below - however I did everything from VS Code. The first step was to install PlatformIO. I just used the plugin for VS Code. You also have to install Git for step 2.
https://meshtastic.org/docs/development/firmware/build/

I got the source from GPSFan link above. If you've not a coder it's a pain but I did get it to work. I was going to wait until Chatter2 shows in the flasher site to do my second device.

**Comment by GPSFan** [comment]
Not something strictly Chatter 2 specific, but with the latest firmware updates, all esp-32 based devices should have better button response.

**Comment by cpuworkshop** [comment]
i need help with my chatter2  im trying to flash 2.3.4 but after its done writing when i restart the chatter the screen is blank

**Comment by GPSFan** [comment]
did you update or wipe?

**Comment by GPSFan** [comment]
Try flashing 2.3.3, that's the latest I have tested with.

**Comment by cpuworkshop** [comment]
i updated and wiped

**Comment by cpuworkshop** [comment]
im using esp tool on chrome

**Comment by GPSFan** [comment]
Did it work on an earlier version?

**Comment by cpuworkshop** [comment]
no

**Comment by cpuworkshop** [comment]
my device is un modified 
i was trying to get one working so i can try to get the keyboard to fully work.
we have alot of new chatter 2.0's from a old project

**Comment by GPSFan** [comment]
I just built the latest 2.3.4 from source in Platformio, loaded it to my Chatter 2 and it works as expected for the quick set of tests I have done, Display, Lora, BLE and GPS interface all work. I no longer have any unmodified Chatter 2s to test against, all of mine have RA-62 Lora radios.
Can you see any boot messages coming out the serial port?

**Comment by cpuworkshop** [comment]
no boot messages on the serial port . what are you using to flash the firmware ? can you send me a copy of what you made in platformino but with the stock firmware

**Comment by cpuworkshop** [comment]
i have flashed 2.3.4 then i flash update bin . after that i restart the device but nothing happens on the screen

**Comment by GPSFan** [comment]
Usually I use Platformio, but have used esptool on occasion. I run Linux, so I have no insight into how Chrome operates, or how esptool works with it. The Web flasher currently does not support the Chatter 2.
Have you flashed any esp-32 based hardware with any other code?
Have you flashed Meshtastic on any other hardware?
Make sure you have good batteries in the Chatter 2.
If you are not seeing anything coming out the serial port then you have a fundamental problem with how or what you are flashing the Chatter 2 with. The bootloader should be sending stuff out the serial port even if the Meshtastic code is corrupted. The Chatter code is stable and has not changed since 2.2.2x.
Get this:
https://github.com/meshtastic/firmware/releases/tag/v2.3.2.63df972
That is the current stable release and works on my Chatter 2.

**Comment by cpuworkshop** [comment]
no i don't hear anything at startup. yes i have flashed a few esp-32 devices . i also have a pair of heltic v3's on meshtastic .. i change the batteries every hour when testing. im able to connect to the port and flaash the firmware but its like its not saving it

**Comment by GPSFan** [comment]
This is really puzzling.
Maybe try a small test program to wiggle one of the GPIO's on the side connector, they are GPIO 2 & 13. If you can load that and the pins wiggle we can eliminate the flashing procedure. Might also try a serial print to validate the serial connection after the flashing is done.

**Comment by cpuworkshop** [comment]
so i gave it another shot and the only firmware i can get to go on the chatter is diy v1 2.3.3.63df972beta .  when i try the chatter 2.34aa3280c.zip it writes but after reboot it has errors and won't boot

**Comment by cpuworkshop** [comment]
i can connect to the mesh app but it doesnt see any nodes or clients

**Comment by GPSFan** [comment]
I just downloaded those 2 versions and will look into it, probably not for a day or two though.

**Comment by GPSFan** [comment]
"so i gave it another shot and the only firmware i can get to go on the chatter is diy v1 2.3.3.63df972beta"
Well, there is no tag with that label, but there is a v2.3.2.63df972 Beta release. If you flashed the diy v1 code, I'm surprised anything functioned. You should have flashed the chatter2 specific code from that release.
Make sure you do a flash erase before flashing anything else.

"when i try the chatter 2.34aa3280c.zip it writes but after reboot it has errors and won't boot"
That was an interim nightly build that is no longer available. I got the latest Alpha:
firmware-chatter2-2.3.4.b14ac77.zip
(it too is no longer available as it was just superseded)
and flashed: firmware-chatter2-2.3.4.b14ac77.bin

Interim nightly builds can often be broken is all sorts of ways, I hardly ever use them, but build my code from sources.
This composite picture shows the flashing process, the contents of the directory I flashed from and the serial output during and just after a power cycle reset. The Chatter 2 worked as expected, and shows other nearby nodes.

Chatter_2
lpha:

**Pull request merged**
