### PR TITLE
[WIP] Add support for Airoha AG3335 GPS

### PR DESCRIPTION
**Pull request by fifieldt**
The Airoha AG3335 is used in Seeed T-1000E Tracker.

This adds automatic detection code, and code to configure its use.

### CODE REVIEW

**Comment by fifieldt** [comment]
I haven't tested this yet, I'm waiting for hardware :)

**Comment by geeksville** [comment]
Hi @fifieldt, while working on heltec tracker power cleanup I noticed this (and similar) in src/GPS.cpp:

```
void GPS::toggleGpsMode()
{
    if (config.position.gps_mode == meshtastic_Config_PositionConfig_GpsMode_ENABLED) {
        config.position.gps_mode = meshtastic_Config_PositionConfig_GpsMode_DISABLED;
        LOG_INFO("User toggled GpsMode. Now DISABLED.\n");
#ifdef GNSS_AIROHA
        if (powerState == GPS_ACTIVE) {
            LOG_DEBUG("User power Off GPS\n");
            digitalWrite(PIN_GPS_EN, !GPS_EN_ACTIVE);
        }
#endif
        disable();
```

I don't understand why this is needed?  It seems to me the standard GPS disable() code will accomplish what is in this ifdef (and a bit more).

Cool work btw!

**Comment by fifieldt** [comment]
Thanks @geeksville :)

Yes - there are a host of GNSS_AIROHA specific branches in the code that I think can probably go away.

Unfortunately I don't actually have a T-1000E with which to test, so I haven't been able to get there. Hopefully, soon.

**Comment by geeksville** [comment]
ooh I have a T-1000E - I'll try this soon!

**Pull request merged**
