### PR TITLE
Get accelerometerThread running from AdminModule.

### PR DESCRIPTION
**Pull request by gjelsoe**
The accelerometerThread fails to start do to new values in `c.payload_variant.device.double_tap_as_button_press` or `c.payload_variant.display.wake_on_tap_or_motion` are not stored in `config.device.double_tap_as_button_press` or `config.display.wake_on_tap_or_motion` before `accelerometerThread->start()` is called, it will compare to old values. AccelerometerThread is also disabled with `disabled()` so it needs to be enabled again before `accelerometerThread->start()`.

[Download firmware-2.5.4.fa79bf1.zip. This artifact will be available for 90 days from creation](https://nightly.link/meshtastic/firmware/actions/artifacts/1992271375.zip)

in `c.payload_variant.device.double_tap_as_button_press` or `c.payload_variant.display.wake_on_tap_or_motion` are not stored in `config.device.double_tap_as_button_press` or `config.display.wake_on_tap_or_motion` before `accelerometerThread->start()` is called, it will compare to old values. AccelerometerThread is also disabled with `disabled()` so it needs to be enabled again before `accelerometerThread->start()`.

[Download firmware-2.5.4.1a0e7ab.zip. This artifact will be available for 90 days from creation](https://nightly.link/meshtastic/firmware/actions/artifacts/1992453904.zip)

in `c.payload_variant.device.double_tap_as_button_press` or `c.payload_variant.display.wake_on_tap_or_motion` are not stored in `config.device.double_tap_as_button_press` or `config.display.wake_on_tap_or_motion` before `accelerometerThread->start()` is called, it will compare to old values. AccelerometerThread is also disabled with `disabled()` so it needs to be enabled again before `accelerometerThread->start()`.

[Download firmware-2.5.4.fa79bf1.zip. This artifact will be available for 90 days from creation](https://nightly.link/meshtastic/firmware/actions/artifacts/1992271375.zip)

in `c.payload_variant.device.double_tap_as_button_press` or `c.payload_variant.display.wake_on_tap_or_motion` are not stored in `config.device.double_tap_as_button_press` or `config.display.wake_on_tap_or_motion` before `accelerometerThread->start()` is called, it will compare to old values. AccelerometerThread is also disabled with `disabled()` so it needs to be enabled again before `accelerometerThread->start()`.

### CODE REVIEW

**Review by caveman99 — APPROVED** [review]

**Comment by caveman99** [comment]
you could also call setIntervalFromNow(0) to start it again. disable just sets the next execution to MAX_UINT

**Comment by gjelsoe** [comment]
> you could also call setIntervalFromNow(0) to start it again. disable just sets the next execution to MAX_UINT

So `accelerometerThread->setIntervalFromNow(0)` would have done the same as `accelerometerThread->enabled = true` ?

**Comment by caveman99** [comment]
> > you could also call setIntervalFromNow(0) to start it again. disable just sets the next execution to MAX_UINT
> 
> So `accelerometerThread->setIntervalFromNow(0)` would have done the same as `accelerometerThread->enabled = true` ?

Err, nope - the enabled is still neccessary, but the start is not :-) It was more like a remark´than a change request.

**Comment by gjelsoe** [comment]
> > > you could also call setIntervalFromNow(0) to start it again. disable just sets the next execution to MAX_UINT
> > 
> > 
> > So `accelerometerThread->setIntervalFromNow(0)` would have done the same as `accelerometerThread->enabled = true` ?
> 
> Err, nope - the enabled is still neccessary, but the start is not :-) It was more like a remark´than a change request.

Don't mind removing it if it's not necessarily.

**Comment by gjelsoe** [comment]
> > > you could also call setIntervalFromNow(0) to start it again. disable just sets the next execution to MAX_UINT
> > 
> > 
> > So `accelerometerThread->setIntervalFromNow(0)` would have done the same as `accelerometerThread->enabled = true` ?
> 
> Err, nope - the enabled is still neccessary, but the start is not :-) It was more like a remark´than a change request.

I've just tested it without `accelerometerThread->start()` and it doesn't work on the Bandit without.
I2Cs doesn't get initialized.

**Pull request merged**
