### PR TITLE
Feature support rak10701 touchscreen

### PR DESCRIPTION
**Pull request by DanielCao0**
## Feature support rak10701 touchscreen
- Add the touch screen driver RAK10701 platform, lib_deps https://github.com/RAKWireless/RAK14014-FT6336U
- Added RAK10701 touch screen virtual keyboard, supporting cannedMessageModule free text

### CODE REVIEW

**Comment by DanielCao0** [comment]
virtual keyboard

**Review by thebentern — APPROVED** [review]

**Comment by thebentern** [comment]
Changes look good. Looks like one of the files needs trunk fmt run on it.

**Comment by thebentern** [comment]
Also please sign the CLA. :-)

**Comment by DanielCao0** [comment]
This pull request was closed due to a problem with the CLA configuration, and a new pull request has been submitted
 Have merged  https://github.com/meshtastic/firmware/pull/4104

**Pull request closed without merging**
