### PR TITLE
Detect charging status by measuring current flow with configured INA219 battery sensor

### PR DESCRIPTION
**Pull request by nebman**
## Detect charging status by measuring current flow with configured INA219 battery sensor

As already described in issue #5226 here is the pull-request

### Intro

Nodes that use an e.g. INA219 for monitoring the battery voltage (explicitly set address in the power settings) can detect the charging status by measuring the current flow across the shunt. The current implementation in AnalogBatteryLevel doesn't make much use of the isCharging() function.

If the current is negative, that indicates the battery is being charged.

This PR adds the functionality to detect the charging status by measuring current flow when the INA address is set as battery monitor.

### Changes to code

- new abstract class CurrentSensor with function getCurrentMa() to not have to request full metrics every time
- minimalistic implementation for the INA219 (I can expand that to the INA3221 and INA260 classes although I can't test those)
- on by default when the power settings have an INA address set
- can be disabled by define DISABLE_INA_CHARGING_DETECTION 
- current flow detection direction can be inverted with INA_CHARGING_DETECTION_INVERT when VIN+ is not wired to the high side (question: any known variants out there with this IC onboard where we could pre-check this?)

### Tests
I tested the branch on two of my custom build NRF52 nodes integrating an INA219. Also tested both extra defines. Works well so far and the correct charging status is displayed on the screen
  
  
Every input is appreciated, especially because I'm no C++ expert ;) Unfortunately the trunk extension keeps crashing in my VS Code

### CODE REVIEW

**Comment by fifieldt** [comment]
Thank you very much for this, very useful first contribution to Meshtastic :)

I think I have a INA3221 lying around here to help test.

What's the best way to wire these things up?

**Comment by nebman** [comment]
Thank you and also thanks for offering your help to test!
To wire this up, you need the classic I2C pins (VCC, GND, SCL, SDA), and splice the INA3221 Channel 1 (if I read that correctly from code) into your plus side power supply line, i.e. VIN1+ to battery positive and VIN1- towards the load/board.  
Be aware there are boards out there with a kinda faulty design, where all channels refer on one side to GND. They can't be used.

As it just happened, the mailman delivered me an INA3221 board some minutes ago :) If you give me some time I might be able to test it myself (also more coding is needed).

**Comment by nebman** [comment]
code for INA3221 is up, using channel 1 for battery voltage and current monitoring, the charging detection works fine

**Comment by fifieldt** [comment]
Hi, apologies. It looks like the devices I have lying around are an INA231 and an INA226. I will try and buy an INA3221

**Comment by fifieldt** [comment]
Oh no! I have messed up the git somehow in my attempt to rebase and perform trunk fixes :'(

**Review by fifieldt — APPROVED** [review]

**Comment by nebman** [comment]
> Oh no! I have messed up the git somehow in my attempt to rebase and perform trunk fixes :'(

I only know some basic git but is there anything I could help with? Worst case we could start with a fresh PR.  

Did you get a chance to test with the INA3221? Meanwhile I got my hands on a INA226 board to complete the trio, but atm unfortunately no node around to test it with

**Comment by fifieldt** [comment]
> I only know some basic git but is there anything I could help with? Worst case we could start with a fresh PR.

Thank you. I think we can just ignore it -- it will all squash into a single commit on merge :) Sorry about that!

**Comment by fifieldt** [comment]
> Did you get a chance to test with the INA3221? Meanwhile I got my hands on a INA226 board to complete the trio, but atm unfortunately no node around to test it with

Alas, no. Though! I do have an INA226 plugged in and on a node right now.

**Comment by fifieldt** [comment]
The INA226 is detecting as an INA260 in current code, so this will require changes in a few more areas.

**Comment by fifieldt** [comment]
I've proposed a change to the protobuf definitions to add support for the INA226: https://github.com/meshtastic/protobufs/pull/635

**Comment by fifieldt** [comment]
Won't merge this for now, since it will fail without the protobuf change, but this is what is needed to add INA226 to auto-detect:

```
diff --git a/src/detect/ScanI2C.h b/src/detect/ScanI2C.h
index 7fe3aac89..2473a6573 100644
--- a/src/detect/ScanI2C.h
+++ b/src/detect/ScanI2C.h
@@ -63,7 +63,8 @@ class ScanI2C
         MAX30102,
         TPS65233,
         MPR121KB,
-        CGRADSENS
+        CGRADSENS,
+        INA226
     } DeviceType;
 
     // typedef uint8_t DeviceAddress;
@@ -127,4 +128,4 @@ class ScanI2C
 
   private:
     bool shouldSuppressScreen = false;
-};
\ No newline at end of file
+};
diff --git a/src/detect/ScanI2CTwoWire.cpp b/src/detect/ScanI2CTwoWire.cpp
index 551b87d27..9a6d9cf3c 100644
--- a/src/detect/ScanI2CTwoWire.cpp
+++ b/src/detect/ScanI2CTwoWire.cpp
@@ -250,8 +250,16 @@ void ScanI2CTwoWire::scanPort(I2CPort port, uint8_t *address, uint8_t asize)
                 registerValue = getRegisterValue(ScanI2CTwoWire::RegisterLocation(addr, 0xFE), 2);
                 LOG_DEBUG("Register MFG_UID: 0x%x", registerValue);
                 if (registerValue == 0x5449) {
-                    logFoundDevice("INA260", (uint8_t)addr.address);
-                    type = INA260;
+                       registerValue = getRegisterValue(ScanI2CTwoWire::RegisterLocation(addr, 0xFF), 2);
+                       LOG_DEBUG("Register DIE_UID: 0x%x", registerValue);
+
+                       if (registerValue == 0x2260) {
+                           logFoundDevice("INA226", (uint8_t)addr.address);
+                       type = INA260;
+                                       } else {
+                           logFoundDevice("INA260", (uint8_t)addr.address);
+                       type = INA260;
+                                       }
                 } else { // Assume INA219 if INA260 ID is not found
                     logFoundDevice("INA219", (uint8_t)addr.address);
                     type = INA219;
@@ -478,4 +486,4 @@ void ScanI2CTwoWire::logFoundDevice(const char *device, uint8_t address)
 {
     LOG_INFO("%s found at address 0x%x", device, address);
 }
-#endif
\ No newline at end of file
+#endif
diff --git a/src/main.cpp b/src/main.cpp
index 2357a00de..85deca602 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -573,6 +573,7 @@ void setup()
     scannerToSensorsMap(i2cScanner, ScanI2C::DeviceType::BMP_3XX, meshtastic_TelemetrySensorType_BMP3XX);
     scannerToSensorsMap(i2cScanner, ScanI2C::DeviceType::BMP_085, meshtastic_TelemetrySensorType_BMP085);
     scannerToSensorsMap(i2cScanner, ScanI2C::DeviceType::INA260, meshtastic_TelemetrySensorType_INA260);
+    scannerToSensorsMap(i2cScanner, ScanI2C::DeviceType::INA226, meshtastic_TelemetrySensorType_INA226);
     scannerToSensorsMap(i2cScanner, ScanI2C::DeviceType::INA219, meshtastic_TelemetrySensorType_INA219);
     scannerToSensorsMap(i2cScanner, ScanI2C::DeviceType::INA3221, meshtastic_TelemetrySensorType_INA3221);
     scannerToSensorsMap(i2cScanner, ScanI2C::DeviceType::MAX17048, meshtastic_TelemetrySensorType_MAX17048);
```

**Comment by nebman** [comment]
> The INA226 is detecting as an INA260 in current code, so this will require changes in a few more areas.

Oh sorry, I think I got it mixed up then with the INA260 which was already implemented in the current code (but not in this PR yet)

**Comment by fifieldt** [comment]
INA226 detection code was merged.

**Comment by fifieldt** [comment]
Works on INA226

**Review by fifieldt — APPROVED** [review]

**Comment by nebman** [comment]
Thanks @fifieldt for adding the INA226, testing and merging the PR. I just tested the master and it works as intended.  
Happy holidays! 🎄

**Comment by fifieldt** [comment]
Thank you for your work!

**Comment by fifieldt** [comment]
Congratulations on an epic first patch. Feel free to join us in the contributors-lounge in discord :)

**Pull request merged**
