### PR TITLE
[Board] Support Heltec LoRa32 v3.2 charge status

### LINKED ISSUE #5127: [Board]: Heltec WiFi LoRa32 V3.2 - new version shows incorrect charge status
### SOC

ESP32

### Lora IC

SX1262

### Product Link

http://community.heltec.cn/t/heltec-wifi-lora32-v3-2-new-revision/16726

### Description

I got the new revision of this board. It has some issues with showing battery information, and shows that it's always plugged into USB. From the Heltec forum, it looks like the charging circuit readout is inverted.

http://community.heltec.cn/t/heltec-wifi-lora32-v3-2-new-revision/16726/5

### PR DESCRIPTION
**Pull request by HarrisonW**
Tested with `pio run -e heltec-v3_2`` and uploading to a v3.2 board. Now shows battery status properly.

fixes #5127

### CODE REVIEW

**Review by fifieldt — APPROVED** [review]
This seems to be the appropriate fix for now

**Comment by thebentern** [comment]
Thanks for the PR. Before we go down this route, I have something sneaky I want to try to hopefully not need two separate variants.

**Comment by caveman99** [comment]
Waiting for the sneak to sneak ... :-)

**Comment by HarrisonW** [comment]
#5196 does this better, but will keep this open if that one doesn't work

**Comment by meekowai** [comment]
I built my own fw 2 days ago with suggested change
`17 #define ADC_CTRL_ENABLED HIGH`
based of master branch and noticed today the board won't keep charging the battery. 
Even tho the cable is plugged in, the battery stars to drain.
Is #5196  fixing this as well?

**Pull request closed without merging**
