### PR TITLE
Update lib/device-ui to protobuffs 2.5.15

### PR DESCRIPTION
**Pull request by ozmullins**
Update the `lib/device-ui` to the commit matching the change in protobuff sizes which introduced the following compiler error.

```
lib/device-ui/source/ViewController.cpp:497:35: error: too many initializers for 'pb_byte_t [233]' {aka 'unsigned char [233]'}
             .want_ack = (to != 0)}});
                                   ^
Compiling .pio/build/t-deck-tft/src/DisplayFormatters.cpp.o
Compiling .pio/build/t-deck-tft/src/FSCommon.cpp.o
*** [.pio/build/t-deck-tft/lib/device-ui/source/ViewController.cpp.o] Error 1
```

Introduced on: https://github.com/meshtastic/firmware/commit/09286a3beb42ef1484e2a5759780a8410def46fc

### CODE REVIEW

**Comment by mverch67** [comment]
This has been done already, see commited https://github.com/meshtastic/device-ui/commit/2f6c7959fd9fd92505c0517a47b9218975abe806

**Comment by ozmullins** [comment]
@mverch67 this commit was bringing the submodule up to date with that commit. That's why I referenced it 😀.

**Comment by mverch67** [comment]
Not needed, as the branch is merged soon.

**Comment by caveman99** [comment]
> @mverch67 this commit was bringing the submodule up to date with that commit. That's why I referenced it 😀.

We are currently bringing our ducks in a row for a proper release of this. Merging this particular PR will lead to a merge conflict later. There is a reason this is not updated here and now.

**Comment by ozmullins** [comment]
Easy, but anyone pulling and building would get that now so just opened a pr; great will be merged soon. 🥳

**Pull request closed without merging**
