### PR TITLE
Possibly forward PKC DMs over MQTT

### PR DESCRIPTION
**Pull request by jp-bennett**

### CODE REVIEW

**Review by thebentern — APPROVED** [review]

**Review by ianmcorvidae — APPROVED** [review]
This looks like the fix for the spot I was looking at (unless we need to do any additional guards when MQTT encryption is turned off?); haven't dug through completely to be sure it's the only spot. We may need to mark the packet as pki_encrypted (even though we're not sure it is) with how the MQTT code is currently written, since I think it chooses the publish topic and such based on that. Or push similar checks to this into there as well

**Comment by jp-bennett** [comment]
@ianmcorvidae I *think* this logic is already present in MQTT itself.

**Comment by JohnathonMohr** [comment]
@jp-bennett just judging from the title - do you expect this to fix #5000? Or is this unrelated?

**Comment by jp-bennett** [comment]
> @jp-bennett just judging from the title - do you expect this to fix #5000? Or is this unrelated?

I believe this is related, yes. Please let me know if this fixes your issue.

**Comment by GUVWAF** [comment]
@jp-bennett I don't think this will do anything, it would only lead to: 
https://github.com/meshtastic/firmware/blob/ad8747d914e670bf7be43dfe3b58f2fda598c7c1/src/mqtt/MQTT.cpp#L540-L542
Because if it was already decoded and it was PKC, `pki_encrypted` would be set.

**Pull request merged**
