### PR TITLE
Add health telemetry module

### PR DESCRIPTION
**Pull request by thebentern**
Adds a new telemetry module covering health aspects - body temperature, oxygen saturation and heart rate. Currently the MLX90614 IR temperature sensor and MAX30102 temperature/oxygen saturation/heart rate sensors are supported.

The module will add a frame to devices with a screen, and broadcast to the mesh based on the set interval.

Fixes https://github.com/meshtastic/firmware/issues/4738

### CODE REVIEW

**Comment by fifieldt** [comment]
For reference - looked up emissivity and cows and humans are both 0.98, so that's a good value if we need to set that for temperature sensors. Pigs also >0.95.  If this needs to go on furry animals like a mouse, then we need to revisit :)

**Comment by fifieldt** [comment]
I just wrote up the MLX90614 temp sensor quickly as an EnvironmentalTelemetry sensor to get it working. It works now. So we can steal the code for HealthTelemetry testing :)

**Comment by fifieldt** [comment]
OK, and there's the MAX30102 - or, at least the temperature bit - working.

**Comment by fifieldt** [comment]
now for the fun bit?

**Comment by fifieldt** [comment]
Big difference when compared with EnvironmentalTelemetry seems to be that we need to get multiple readings in order to get SPO2 or heart rate. This might end up being more like GPS where we turn it on to get a 'fix', and then sleep it.

**Comment by fifieldt** [comment]
After the last set of changes, spO2 and temperature both look accurate.

Heart rate is too high - tried increasing bus speed to 400Khz but no change, also tried taking 8 seconds (original: 4 secs) of samples and no change.

Also, only works on nrf52 due to some hard-coded references to SCL/SDA.

**Comment by fifieldt** [comment]
Fixed the SCL/SDA stuff by switching libraries for MAX90614.

Screen works!

**Comment by fifieldt** [comment]
"Common libs for environmental measurements in telemetry module are not included in native / portduino" - which is why those builds are failing. Need to fix.

**Comment by fifieldt** [comment]
Also need to wrap the screen stuff in a HAS SCREEN it seems.

**Comment by fifieldt** [comment]
"It works!"

**Comment by HarukiToreda** [comment]
any sneak peek on how the screen will display this data?

**Comment by thebentern** [comment]
DEBUG | ??:??:?? 104 [HealthTelemetryModule] heart_rate=187(1), sp02=100(1)(Sending): temperature=33.500000, heart_bpm=187, spO2=100
DEBUG | ??:??:?? 104 [HealthTelemetryModule] Partially randomized packet id 424126784
INFO  | ??:??:?? 104 [HealthTelemetryModule] Sending packet to mesh

**Pull request merged**
