### PR TITLE
Fix bootloop for T-Watch S3 when using WiFi

### LINKED ISSUE #4981: [Bug]: T-Watch S3 is looping after Wifi enabled
### Category

WiFi

### Hardware

T-Watch

### Firmware Version

2.5.5.e18 (alpha) and 2.5.4.8d (stable)

### Description

watch is looping and cannot enable wifi. tried to enable wifi to get time synced (other bug), but wifi does not work

### Relevant log output

```Shell
none
```

### PR DESCRIPTION
**Pull request by todd-herbert**
Fixes #4981 (hopefully)

I can reproduce and solve the issue on my makeshift T-Watch test device.
It'd be good to get this checked on the actual hardware just to confirm.

### CODE REVIEW

**Review by fifieldt — APPROVED** [review]
Can't hurt!

**Comment by Guytantak** [comment]
I have the same issue. Do you have found a solution ? I don't know how github works 😅

**Comment by fifieldt** [comment]
Hi @Guytantak , not to worry - I barely understand github most days too.

If you get the latest alpha release from https://flasher.meshtastic.org it will include this fix.

**Comment by Guytantak** [comment]
Oh ! Merci pour l'info, j'essaie ça demain. J'espère pouvoir connecter la
montre à un port com 😉😊

Le mar. 12 nov. 2024, 03:02, Tom Fifield ***@***.***> a
écrit :

**Pull request merged**
