### PR TITLE
fix compiler warnings in NodeDB.h

### PR DESCRIPTION
**Pull request by mverch67**
The gcc arm compiler from the arm-gnu-toolchain seems a little bit more picky about missing newline endings at the very end of a file (when there's a #define with backslash-newline). When compiling on a raspberry pi it spits out hundreds of warnings, one for every file that includes NodeDB.h .

```
Compiling .pio/build/t-deck/src/graphics/EInkDisplay2.cpp.o
In file included from src/GPSStatus.h:2,
                 from src/main.h:3,
                 from src/detect/ScanI2CTwoWire.cpp:9:
src/mesh/NodeDB.h:213:130: warning: backslash-newline at end of file
 #define Module_Config_size                                                                                                       \
                                                                                                                                   
Compiling .pio/build/t-deck/src/graphics/EInkDynamicDisplay.cpp.o
Compiling .pio/build/t-deck/src/graphics/Screen.cpp.o
In file included from src/GPSStatus.h:2,
                 from src/gps/GPS.h:3,
                 from src/gps/GPS.cpp:1:
src/mesh/NodeDB.h:213:130: warning: backslash-newline at end of file
 #define Module_Config_size                                                                                                       \
                                                                                                                                   
In file included from src/GPSStatus.h:2,
                 from src/main.h:3,
                 from src/gps/NMEAWPL.h:3,
                 from src/gps/NMEAWPL.cpp:1:
src/mesh/NodeDB.h:213:130: warning: backslash-newline at end of file
 #define Module_Config_size                                                                                                       \
                                                                                                                                   
In file included from src/GPSStatus.h:2,
                 from src/main.h:3,
                 from src/gps/RTC.cpp:4:
src/mesh/NodeDB.h:213:130: warning: backslash-newline at end of file
 #define Module_Config_size                                                                                                       \
                                                                                                                                   
In file included from src/mesh/Channels.h:4,
                 from src/mesh/MeshModule.h:3,
                 from src/graphics/Screen.h:57,
                 from src/graphics/Screen.cpp:22:
src/mesh/NodeDB.h:213:130: warning: backslash-newline at end of file
 #define Module_Config_size      
```

### CODE REVIEW

**Comment by caveman99** [comment]
That's on every compile now, not only on ARM. The problem is trunk will undo your fix. I solved it by including a comment at the end of the file.

**Comment by caveman99** [comment]
on the apollo3 branch i added

`// Please do not remove this comment, it makes trunk and compiler happy at the same time.`

**Review by caveman99 — APPROVED** [review]

**Comment by markbirss** [comment]
> The gcc arm compiler from the arm-gnu-toolchain seems a little bit more picky

I had a look at musl riscv64 native compilation (Linux 3.20.0_alpha20240315 (edge)) - gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309

was able to get wheels compiled for grpcio compilation starts fixed some missing headers but the libraries also wont compile.....

image

**Comment by mverch67** [comment]
> > The gcc arm compiler from the arm-gnu-toolchain seems a little bit more picky

#include <time.h> is missing

**Pull request merged**
