### PR TITLE
Check Position Request for Primary Channel

### PR DESCRIPTION
**Pull request by jp-bennett**
Prevents leaking location data to secondary channels.

### CODE REVIEW

**Review by thebentern — APPROVED** [review]

**Review by GUVWAF — CHANGES_REQUESTED** [review]
I now remember that there is a way to ignore requests, which seems like a better approach than overriding `sendResponse` with largely duplicated logic and exposing `currentReply` to all modules. This should be as simple as doing the if-condition within PositionModule's `allocReply`, set `ignoreRequest` to true and return NULL (see https://github.com/meshtastic/firmware/blob/master/src/modules/NodeInfoModule.cpp#L62). Can you do it in that way?

**Comment by GUVWAF** [comment]
Ah, you're right and you mentioned that already, sorry. Your other approach sounds good and would be cleaner indeed.

**Comment by GUVWAF** [comment]
You could set `ignoreRequest` to true in `handleReceivedProtobuf` and return NULL in `allocReply` if this is the case.

**Comment by jp-bennett** [comment]
@GUVWAF Seems to work as expected. Agreed, this is a much better approach.

**Review by GUVWAF — APPROVED** [review]
@jp-bennett Great! Looks good to me.

**Pull request merged**
