### PR TITLE
Added "Hops away" on display

### PR DESCRIPTION
**Pull request by capslockapocalypse**
Added in logic that displays "hops away" instead of signal strength on the display when the node is more than 0 hops away.
Any feedback to tidy up is appreciated.

### CODE REVIEW

**Review by caveman99 — APPROVED** [review]

**Review by thebentern — APPROVED** [review]

**Comment by capslockapocalypse** [comment]
Apologies If I'm not doing this right, first time using github and contributing. I'm assuming I need to get the Trunk Check Runner to pass? and that it's hanging on the extensions file.

**Comment by thebentern** [comment]
> Apologies If I'm not doing this right, first time using github and contributing. I'm assuming I need to get the Trunk Check Runner to pass? and that it's hanging on the extensions file.

Everything looks good on that front. You just need to revert your commit to the .vscode/extensions.json file. :-)

**Comment by capslockapocalypse** [comment]
Thank you for your help and patience, if this doesn't work I'll just retry the whole pull request.

**Review by thebentern — APPROVED** [review]

**Comment by HarukiToreda** [comment]
> Added in logic that displays "hops away" instead of signal strength on the display when the node is more than 0 hops away. Any feedback to tidy up is appreciated.

do you have some screenshots to show it looks?

**Pull request merged**
