### PR TITLE
Only return a time if we have a fix

### PR DESCRIPTION
**Pull request by fifieldt**
NMEA GGA Messages have a GPS Quality Indicator which indicates whether a GPS fix was achieved. Use this to determine whether we should attempt to set a time or not.

Also, fix up some of the custom airoha code and comments.

### CODE REVIEW

**Comment by fifieldt** [comment]
the check failures don't look like my fault, I swear!

**Comment by jp-bennett** [comment]
We broke web again! >< Yeah, not @fifieldt 's fault.

**Review by caveman99 — APPROVED** [review]

**Comment by fifieldt** [comment]
Is this patch still necessary after 
#4705 
And 
#4704

?

This could delay setting a good time and the issues we've seen in the past are probably well solved by the other patches...

**Comment by jp-bennett** [comment]
> Is this patch still necessary after 
> #4705 
> And 
> #4704
> 
> ?
> 
> This could delay setting a good time and the issues we've seen in the past are probably well solved by the other patches...

I don't think either of those would address a timestamp in the future, where this one seems to.

**Comment by thebentern** [comment]
@fifieldt on voice chat yesterday we also discussed simply relaxing the time aggressive guarding window of 12 hours when a GPS is detected. That would solve this issue in a somewhat different way. We would have a temporarily inaccurate time until a good fix is acquired and then the GPS would correct the time.

**Comment by fifieldt** [comment]
Closing this now the alternate fix is in :) Or at least if I understand correctly!

**Pull request closed without merging**
