### PR TITLE
Update variant.h enable OLED Screen for HT-CT62

### PR DESCRIPTION
**Pull request by markbirss**
Enable OLED for use

### CODE REVIEW

**Comment by arzaman** [comment]
Hi 
tryng to use HT-CT62 module with ESP32 C3 and SX1262 for a custom HW board and I want to make it fully compatible with the "official" variant and web flasher but I have some questions about the GPIO assignement and reference HW schema you use

this is the reference design from heltec that I assume is used for the "esp dev backplane"

https://resource.heltec.cn/download/HT-CT62/HT-CT62_Reference_Design.pdf

image

from that schema it seems there are some incongruences with the variant file

In particular GPIO 0 and 1 are used for external oscillator not for the I2C bus

`#define I2C_SDA 1
#define I2C_SCL 0

#define BUTTON_PIN 9
#define BUTTON_NEED_PULLUP

// LED flashes brighter
// https://resource.heltec.cn/download/HT-CT62/HT-CT62_Reference_Design.pdf
#define LED_PIN 18 // LED
#define LED_INVERTED 1

#define HAS_SCREEN 1
#define HAS_GPS 0
#undef GPS_RX_PIN
#undef GPS_TX_PIN

#undef LORA_SCK
#undef LORA_MISO
#undef LORA_MOSI
#undef LORA_CS

#define USE_SX1262
#define LORA_SCK 10
#define LORA_MISO 6
#define LORA_MOSI 7
#define LORA_CS 8
#define LORA_DIO0 RADIOLIB_NC
#define LORA_RESET 5
#define LORA_DIO1 3
#define LORA_DIO2 RADIOLIB_NC
#define LORA_BUSY 4
#define SX126X_CS LORA_CS
#define SX126X_DIO1 LORA_DIO1
#define SX126X_BUSY LORA_BUSY
#define SX126X_RESET LORA_RESET
#define SX126X_DIO2_AS_RF_SWITCH
#define SX126X_DIO3_TCXO_VOLTAGE 1.8`

can you clarify what is the HW reference for that variant ? 
Is it compatible with the "esp dev backplane" ??

thanks for support and clarification

Davide

**Comment by markbirss** [comment]
@arzaman 

yes, variant for use with the heltec provided backplane

https://heltec.org/product/esp-dev-backplane/

#2741

**Comment by arzaman** [comment]
Thanks for the quick reply!

I initially thought it was for the "dev backplane"! 
What misled me was assuming that the reference design equaled the dev backplane, so included the external crystal oscillator that conflicts with I2C

I've just ordered one backplane to experiment with...

One more question, since you've been so helpful: If I want to use the module without a display, meaning I won't connect the display on the I2C bus, do you know if the firmware will still work or will it crash/block? Should I recompile with the HAS_SCREEN 0 option?

thanks
Davide

**Comment by markbirss** [comment]
@arzaman 

Changing HAS_SCREEN=0 is fine for headless use but think it works fine without oled even HAS_SCREEN =1

It was changed to 1 since even if you had connected a oled the gui would not show

If you undefine the I2C pins all together bootup will take long

**Comment by markbirss** [comment]
Thr oled display will not show a bootup logo or work when HAS_SCREEN=0

**Pull request merged**
