### PR TITLE
Add new port number for airborne application(s)

### PR DESCRIPTION
**Pull request by pjalocha**
I am very sorry, I forgot to actually change the name of the new port !
I fixed it in the next push to the same branch, but I am not sure how to proceed now.
Sorry for the mess.

I propose a new port number for airborne applications like OGN-Tracer or FANET or ADS-L whch have well establilshed compact position packet formats. It is more efficient to put position in this format, which takes like 16 bytes for OGN than use the GPS generic format where many elements are missing like climb rate ro turn rate.

The new port number would allow efficient (low rate) position reports by objects like amateur balloons.

The formatting would be simple: I define ID's for particulat packet type and they would be embedded as a pack of bytes, the decoding of the pack would follow the particular system.

If this gets accepted, I will proceed to define those ID's

Thank you.

BTW. I am beta-receiving Meshtantic on ground receivers of the Open Glider Network (OGN) and I wonder if it would be worth to upload this traffic to a server of yours ?

### CODE REVIEW

**Review by fifieldt — CHANGES_REQUESTED** [review]
As @gjelsoe said, this change needs to be ade in the protobufs repo.

**Comment by pjalocha** [comment]
Thank you, I will make the changes, and push them.

**Comment by pjalocha** [comment]
I have done the hopefully correct now change in the meshtantic/protobufs and made a pull request there.
You might then remove this pull request and treat the other one.
Thank you.

**Comment by caveman99** [comment]
this is a null change. closing in favor of protobuf PR's

**Pull request closed without merging**
