### PR TITLE
fix: don't broadcast public keys if the user is licensed

### PR DESCRIPTION
**Pull request by andrekir**
prevents NodeInfo broadcasts with public keys when the user is licensed.

### CODE REVIEW

**Review by thebentern — APPROVED** [review]

**Comment by jp-bennett** [comment]
Do we need this, with the is_licensed change I pushed earlier?

**Comment by JohnathonMohr** [comment]
Please excuse my ignorance, but I'm curious to learn why this is necessary. I understand ham has to operate unencrypted, so the licensed node can't send anything encrypted, but why prevent another non-licensed node from sending something encrypted. Must a licensed node also not _receive_ anything encrypted?

**Comment by thebentern** [comment]
> Do we need this, with the is_licensed change I pushed earlier?

Not sure your change will have an effect if they already have keys generated.

**Comment by andrekir** [comment]
> Do we need this, with the is_licensed change I pushed earlier?

yes. public keys are still being sent in the NodeInfo broadcasts when `is_licensed` is true.

**Comment by jp-bennett** [comment]
> Please excuse my ignorance, but I'm curious to learn why this is necessary. I understand ham has to operate unencrypted, so the licensed node can't send anything encrypted, but why prevent another non-licensed node from sending something encrypted. Must a licensed node also not _receive_ anything encrypted?

Last time I checked, I came to the conclusion that it was a problem, yes. Of course I can't currently find that source.

**Comment by jp-bennett** [comment]
> > Do we need this, with the is_licensed change I pushed earlier?
> 
> yes. public keys are still being sent in the NodeInfo broadcasts when `is_licensed` is true.

Got it. Yeah, looks good then.

**Comment by fromthebeanbag** [comment]
I tried to find the legislative answer to amateur radio and encryption and only went down a rabbit hole. In Australia atleast from https://www.acma.gov.au/amateur-radio-operating-procedures I found the following. 

But receiving signals as an amateur would mean the other party could only be another amateur and thus only unencrypted anyway. This not allowing reception of unencrypted would just be additional checks and balances.

Except

Encryption/scrambling
Transmissions from an amateur station must not be encrypted or scrambled, except for signals used to control a satellite, signals used to control a remote amateur station or by stations participating in emergency services operations or exercises.

Re-transmission
If you re-transmit another station’s transmission, you must have the other station’s permission and indicate it is a retransmission.

**Pull request merged**
