### PR TITLE
Rainbow Light Show with NCP5623 for External Notifications

### PR DESCRIPTION
**Pull request by pdxlocations**
This PR enables a pulsing Red, Green, Blue, Yellow, Purple, Cyan, and White light when messages are received.  Requires NCP5623 (RAK14001) and attached battery.

### CODE REVIEW

**Comment by pdxlocations** [comment]
https://github.com/meshtastic/firmware/assets/117498748/50a5f965-dc73-4982-b062-8eb8c7a434d6

**Comment by garthvh** [comment]
Love it!

**Review by thebentern — APPROVED** [review]
Looks great! Much better than my VERY advanced modulo LED flashing algorithm 💥

**Comment by pdxlocations** [comment]
> Looks great! Much better than my VERY advanced modulo LED flashing algorithm 💥

It was a good algorithm, I mapped it's values to fully appreciate it.
image

**Comment by mc-hamster** [comment]
wow

**Comment by pdxlocations** [comment]
I meant to ask, is it necessary to credit the source I used as a base for this code?
https://github.com/kc9zda/NCP5623/blob/master/examples/NCP5623_RampUp/NCP5623_RampUp.ino

**Comment by mc-hamster** [comment]
> I meant to ask, is it necessary to credit the source I used as a base for this code? https://github.com/kc9zda/NCP5623/blob/master/examples/NCP5623_RampUp/NCP5623_RampUp.ino

We should check on the license for answers of that nature. For this project, it is:

https://github.com/kc9zda/NCP5623/blob/master/LICENSE.txt

**Comment by garthvh** [comment]
MIT does not require attribution

**Review by caveman99 — APPROVED** [review]

**Pull request merged**
