### PR TITLE
Change T-Deck TFT from green to white for better readibility

### PR DESCRIPTION
**Pull request by joneyes**
T-Deck screen is almost impossible to read in sunshine.
TFTDisplay.cpp line 12 amended to take color565 values to FF - white.
(this my first go at a pull req.)

### CODE REVIEW

**Comment by mverch67** [comment]
Don't commit .extensions and .settings! These need to be reverted before any commit.

**Review by thebentern — CHANGES_REQUESTED** [review]
Remove the extra file changes

**Comment by joneyes** [comment]
I discarded the two outstanding file chnages. Hope this was the correct thing to do. (Noob)

**Comment by ChDel** [comment]
Why is this closed? It was a great start to better readability…

**Comment by bobricius** [comment]
I am not sure but maybe it is something similar already implemented

etc PicomputerS3 have in variant.h

// Picomputer gets a white on black display
#define TFT_MESH COLOR565(0xFF, 0xFF, 0xFF)

this line for white color

**Comment by joneyes** [comment]
I discarded changes to two surplus files and it closed.
So probably something I did being a noob.
I'll take another look later in the week when I am back home



Regards
Jon



-------- Original message --------
From: Peter Misenko ***@***.***>
Date: 30/04/2024 16:57 (GMT+00:00)
To: meshtastic/firmware ***@***.***>
Cc: Jon Eyes ***@***.***>, State change ***@***.***>
Subject: Re: [meshtastic/firmware] Change T-Deck TFT from green to white for better readibility (PR #3729)


I am not sure but maybe it is something similar already implemented

etc PicomputerS3 have in variant.h

// Picomputer gets a white on black display
#define TFT_MESH COLOR565(0xFF, 0xFF, 0xFF)

this line for white color

**Pull request closed without merging**
