### PR TITLE
Disable deep sleep for nRF  and force shutdown for RAK463x on discharged battery

### PR DESCRIPTION
**Pull request by D4rk4**
Fix for https://github.com/meshtastic/firmware/issues/2022

### CODE REVIEW

**Comment by caveman99** [comment]
I'm curious, is this really triggering for you? it wants 10 samples below min_battery and if one of those is above it will start counting over at zero. If it is triggering there may be some underlying problem in the ADC routines.

**Comment by D4rk4** [comment]
@caveman99 yes it's shit my node =(
Please give me time for sanity validation of this fix in different conditions.

**Comment by caveman99** [comment]
Sure, i converted your PR to a draft, let's get to the bottom of this.

**Review by caveman99 — APPROVED** [review]
We need to investigate the measurements further, this will improve user experience for the time being.

**Pull request merged**
