### PR TITLE
When talking via serial, encapsulate log messages in protobufs if necessary

### PR DESCRIPTION
**Pull request by geeksville**
Instead of just forcing all logging off.
This is required for the upcoming power profiling stuff (because we want to also capure logs in sync with the power changes).  It is also generally useful because you can now see debug info on the serial port even after/while talking to the device via our API.  For instance - python client has been tweaked to understand LogRecord (and old python clients silently ignore LogRecords if seen):

(shows debug messages from device side during the initial config flow)
```
kevinh@kdesktop:~/development/meshtastic/meshtastic-python$ poetry run meshtastic --info --seriallog stdout
Client wants config, nonce=159918409
Got 4 files in manifest
Starting API client config
getFromRadio=STATE_SEND_MY_INFO
getFromRadio=STATE_SEND_OWN_NODEINFO
getFromRadio=STATE_SEND_METADATA
getFromRadio=STATE_SEND_CHANNELS
getFromRadio=STATE_SEND_CHANNELS
getFromRadio=STATE_SEND_CHANNELS
getFromRadio=STATE_SEND_CHANNELS
getFromRadio=STATE_SEND_CHANNELS
getFromRadio=STATE_SEND_CHANNELS
getFromRadio=STATE_SEND_CHANNELS
getFromRadio=STATE_SEND_CHANNELS
getFromRadio=STATE_SEND_CONFIG
getFromRadio=STATE_SEND_CONFIG
getFromRadio=STATE_SEND_CONFIG
getFromRadio=STATE_SEND_CONFIG
getFromRadio=STATE_SEND_CONFIG
getFromRadio=STATE_SEND_CONFIG
getFromRadio=STATE_SEND_CONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_MODULECONFIG
getFromRadio=STATE_SEND_OTHER_NODEINFOS
Done sending nodeinfos
getFromRadio=STATE_SEND_FILEMANIFEST
getFromRadio=STATE_SEND_FILEMANIFEST
getFromRadio=STATE_SEND_COMPLETE_ID
Connected to radio

Owner: Meshtastic 9f6e (9f6e)
My info: { "myNodeNum": 3661668206, "minAppVersion": 30200, "rebootCount": 0 }
Metadata: { "firmwareVersion": "2.3.15.f37bed4f", "deviceStateVersion": 22, "canShutdown": true, "hasBluetooth": true, "positionFlags": 811, "hwModel": "WIO_WM1110", "hasWifi": false, "hasEthernet": false, "role": "CLIENT", "hasRemoteHardware": false }

Nodes in mesh: {
  "!da409f6e": {
    "num": 3661668206,
    "user": {
      "id": "!da409f6e",
      "longName": "Meshtastic 9f6e",
      "shortName": "9f6e",
      "macaddr": "dd:27:da:40:9f:6e",
      "hwModel": "WIO_WM1110"
    },
    "position": {
      "time": 1719588590
    },
    "lastHeard": 1719588590,
    "deviceMetrics": {
      "batteryLevel": 101,
      "uptimeSeconds": 45
    }
  }
}

Preferences: {
  "device": { ...
}

Channels:
  Index 0: PRIMARY psk=default { "psk": "AQ==", "moduleSettings": { "positionPrecision": 32, "isClientMuted": false }, "channelNum": 0, "name": "", "id": 0, "uplinkEnabled": false, "downlinkEnabled": false }

Primary channel URL: https://meshtastic.org/e/#CgcSAQE6AgggEgoIAUADSAFQHmgB

PACKET FROM PHONE (id=0xeaf2062c fr=0x00 to=0xff, WantAck=0, HopLim=3 Ch=0x0 Portnum=3)
handleReceived(USER) (id=0xeaf2062c fr=0x00 to=0xff, WantAck=0, HopLim=3 Ch=0x0 Portnum=3 rxtime=1719588591)
Module 'position' wantsPacket=1
Received position from=0x0, id=0xeaf2062c, portnum=3, payloadlen=5
Incoming update from MYSELF
Setting local position: lat=0 lon=0 time=1719588591 timestamp=0
POSITION node=da409f6e l=5 lat=0 lon=0 msl=0 hae=0 geo=0 pdop=0 hdop=0 vdop=0 siv=0 fxq=0 fxt=0 pts=0 time=1719588591
Current RTC quality: NTP. Ignoring time of RTC quality of NTP
updatePosition SPECIAL time setting time=1719588591
Node status update: 1 online, 1 total
Module 'position' considered
Module 'routing' wantsPacket=1
Received routing from=0x0, id=0xeaf2062c, portnum=3, payloadlen=5
Routing sniffing (id=0xeaf2062c fr=0x00 to=0xff, WantAck=0, HopLim=3 Ch=0x0 Portnum=3 rxtime=1719588591)
Module 'routing' considered
localSend to channel 0
*** A newer version v2.3.12 is available! Consider running "pip install --upgrade meshtastic" ***


```

This checkin chain includes some noop merges from changes I merged from different pr-branches.  I recommend looking at the 'files changed' to see just my changes.

### CODE REVIEW

**Comment by geeksville** [comment]
btw: I have a [change](https://github.com/geeksville/Meshtastic-protobufs/commit/9d747b6cf08e2762fdf9530173a7ff825b9daa90) to increase the size of LogRecords (which is 'free') coming in when I finish the powermon PR (which is soonish).  But that change isn't required for this feature.

**Comment by thebentern** [comment]
> btw: I have a [change](https://github.com/geeksville/Meshtastic-protobufs/commit/9d747b6cf08e2762fdf9530173a7ff825b9daa90) to increase the size of LogRecords (which is 'free') coming in when I finish the powermon PR (which is soonish). But that change isn't required for this feature.

That is a good change. I may consider pushing some of the BLE logs over to this. The existing limits were too restrictive to use in the current state of the logs.

**Review by thebentern — APPROVED** [review]

**Comment by andrekir** [comment]
love seeing LogRecord being put to use! could we later expand this to other interfaces like TCP/IP?

**Comment by geeksville** [comment]
I just updated to merge with the changes in #4199.  Cool to merge into master?

**Comment by geeksville** [comment]
@andrekir with this change it automatically happens for TCP also (assuming the client is the python meshtastic client).  It happens for any streaming interface (not just serial)

**Comment by geeksville** [comment]
@andrekir oops I was wrong.  To work on TCP and the JTAG link some refactoring is needed.  In a couple of days I'll send in a PR to do that.  I'm moving all of the logging goo out of RedirectablePrint (which wasn't really the ideal place originally - and certainly not now that we are sending logs to possibly 3 or 4 different places).  It cleans things up a lot and will nicely make API access work over the JTAG link and let TCP links receive logs.  Away hiking today and tomorrow.

**Pull request merged**
